CREATE TABLE "SALES_ORDER" (
	"SALES_ORDER_ID"	NUMBER(18,0)		NOT NULL,
	"SALES_ORDER_NO"	VARCHAR2(30 CHAR)		NOT NULL,
	"BUSINESS_DATE"	DATE		NOT NULL,
	"PARTNER_ID"	NUMBER(18,0)		NULL,
	"PARTNER_NAME"	VARCHAR2(100 CHAR)		NULL,
	"WAREHOUSE_ID"	NUMBER(18,0)		NOT NULL,
	"WAREHOUSE_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"ASSIGNEE_ID"	NUMBER(18,0)		NULL,
	"ASSIGNEE_NAME"	VARCHAR2(100 CHAR)		NULL,
	"DUE_DATE"	DATE		NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"PROGRESS_STATUS"	VARCHAR2(20 CHAR)	DEFAULT 'IN_PROGRESS'	NOT NULL,
	"UPDATED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL,
	"DELETED_YN"	VARCHAR2(1 CHAR)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "SALES_ORDER"."SALES_ORDER_ID" IS '주문서를 식별하는 ID';

COMMENT ON COLUMN "SALES_ORDER"."SALES_ORDER_NO" IS '주문서 번호';

COMMENT ON COLUMN "SALES_ORDER"."BUSINESS_DATE" IS '주문 업무 기준 날짜';

COMMENT ON COLUMN "SALES_ORDER"."PARTNER_ID" IS '연결된 거래처를 식별하는 ID';

COMMENT ON COLUMN "SALES_ORDER"."PARTNER_NAME" IS '전표에 보존한 당시 거래처 이름';

COMMENT ON COLUMN "SALES_ORDER"."WAREHOUSE_ID" IS '연결된 창고를 식별하는 ID';

COMMENT ON COLUMN "SALES_ORDER"."WAREHOUSE_NAME" IS '전표에 보존한 당시 창고 이름';

COMMENT ON COLUMN "SALES_ORDER"."ASSIGNEE_ID" IS '선택한 담당자를 참조하는 ID';

COMMENT ON COLUMN "SALES_ORDER"."ASSIGNEE_NAME" IS '전표에 보존한 당시 담당자명';

COMMENT ON COLUMN "SALES_ORDER"."DUE_DATE" IS '납품하기로 예정한 날짜';

COMMENT ON COLUMN "SALES_ORDER"."NOTE" IS '전표에 남기는 참고 내용';

COMMENT ON COLUMN "SALES_ORDER"."PROGRESS_STATUS" IS 'UNCONFIRMED: 미확인, IN_PROGRESS: 진행중, COMPLETED: 완료, 기본값: IN_PROGRESS';

COMMENT ON COLUMN "SALES_ORDER"."UPDATED_AT" IS '마지막으로 변경한 시각';

COMMENT ON COLUMN "SALES_ORDER"."DELETED_YN" IS '삭제 시: Y, 기본값: N';

CREATE TABLE "SHIPMENT_LINE" (
	"SHIPMENT_LINE_ID"	NUMBER(18,0)		NOT NULL,
	"SHIPMENT_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"SPECIFICATION"	VARCHAR2(100 CHAR)		NULL,
	"UNIT"	VARCHAR2(20 CHAR)		NULL,
	"QUANTITY"	NUMBER(18,3)		NOT NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"DELETED_YN"	VARCHAR2(1 CHAR)	DEFAULT 'N'	NOT NULL,
	"SHIP_INSTRUCTION_LINE_ID"	NUMBER(18,0)		NULL
);

COMMENT ON COLUMN "SHIPMENT_LINE"."SHIPMENT_LINE_ID" IS '출하 품목 행을 식별하는 ID';

COMMENT ON COLUMN "SHIPMENT_LINE"."SHIPMENT_ID" IS '이 행이 속한 출하를 참조하는 ID';

COMMENT ON COLUMN "SHIPMENT_LINE"."ITEM_ID" IS '연결된 품목을 식별하는 ID';

COMMENT ON COLUMN "SHIPMENT_LINE"."ITEM_NAME" IS '행에 보존한 당시 품목 이름';

COMMENT ON COLUMN "SHIPMENT_LINE"."SPECIFICATION" IS '행에 보존한 당시 품목 규격';

COMMENT ON COLUMN "SHIPMENT_LINE"."UNIT" IS '거래 당시 품목의 수량 단위';

COMMENT ON COLUMN "SHIPMENT_LINE"."QUANTITY" IS '입력한 품목 수량';

COMMENT ON COLUMN "SHIPMENT_LINE"."NOTE" IS '출하상세행 비고';

COMMENT ON COLUMN "SHIPMENT_LINE"."DELETED_YN" IS '삭제 시: Y, 기본값: N';

COMMENT ON COLUMN "SHIPMENT_LINE"."SHIP_INSTRUCTION_LINE_ID" IS '원출하지시서의 품목 행을 참조하는 ID';

CREATE TABLE "SHIPMENT" (
	"SHIPMENT_ID"	NUMBER(18,0)		NOT NULL,
	"SHIPMENT_NO"	VARCHAR2(30 CHAR)		NOT NULL,
	"BUSINESS_DATE"	DATE		NOT NULL,
	"PARTNER_ID"	NUMBER(18,0)		NULL,
	"PARTNER_NAME"	VARCHAR2(100 CHAR)		NULL,
	"WAREHOUSE_ID"	NUMBER(18,0)		NOT NULL,
	"WAREHOUSE_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"ASSIGNEE_ID"	NUMBER(18,0)		NULL,
	"ASSIGNEE_NAME"	VARCHAR2(100 CHAR)		NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"DELIVERY_CONTACT"	VARCHAR2(30 CHAR)		NULL,
	"DELIVERY_POSTAL_CODE"	VARCHAR2(20 CHAR)		NULL,
	"DELIVERY_ADDRESS"	VARCHAR2(300 CHAR)		NULL,
	"PROGRESS_STATUS"	VARCHAR2(20 CHAR)	DEFAULT 'CONFIRMED'	NOT NULL,
	"UPDATED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL,
	"DELETED_YN"	VARCHAR2(1 CHAR)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "SHIPMENT"."SHIPMENT_ID" IS '출하를 식별하는 ID';

COMMENT ON COLUMN "SHIPMENT"."SHIPMENT_NO" IS '출하 번호';

COMMENT ON COLUMN "SHIPMENT"."BUSINESS_DATE" IS '출하 업무 기준 날짜';

COMMENT ON COLUMN "SHIPMENT"."PARTNER_ID" IS '연결된 거래처를 식별하는 ID';

COMMENT ON COLUMN "SHIPMENT"."PARTNER_NAME" IS '전표에 보존한 당시 거래처 이름';

COMMENT ON COLUMN "SHIPMENT"."WAREHOUSE_ID" IS '연결된 창고를 식별하는 ID';

COMMENT ON COLUMN "SHIPMENT"."WAREHOUSE_NAME" IS '전표에 보존한 당시 창고 이름';

COMMENT ON COLUMN "SHIPMENT"."ASSIGNEE_ID" IS '선택한 담당자를 참조하는 ID';

COMMENT ON COLUMN "SHIPMENT"."ASSIGNEE_NAME" IS '전표에 보존한 당시 담당자명';

COMMENT ON COLUMN "SHIPMENT"."NOTE" IS '전표에 남기는 참고 내용';

COMMENT ON COLUMN "SHIPMENT"."DELIVERY_CONTACT" IS '전표에 저장한 배송지 연락처';

COMMENT ON COLUMN "SHIPMENT"."DELIVERY_POSTAL_CODE" IS '전표에 저장한 배송지 우편번호';

COMMENT ON COLUMN "SHIPMENT"."DELIVERY_ADDRESS" IS '전표에 저장한 배송지 주소';

COMMENT ON COLUMN "SHIPMENT"."PROGRESS_STATUS" IS 'UNCONFIRMED: 미확인, CONFIRMED: 확인, 기본값: CONFIRMED';

COMMENT ON COLUMN "SHIPMENT"."UPDATED_AT" IS '마지막으로 변경한 시각';

COMMENT ON COLUMN "SHIPMENT"."DELETED_YN" IS '삭제 시: Y, 기본값: N';

CREATE TABLE "STOCK_MOVEMENT" (
	"MOVEMENT_ID"	NUMBER(18,0)		NOT NULL,
	"SALE_ID"	NUMBER(18,0)		NULL,
	"SALE_LINE_ID"	NUMBER(18,0)		NULL,
	"WAREHOUSE_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_ID"	NUMBER(18,0)		NOT NULL,
	"QUANTITY_DELTA"	NUMBER(18,3)		NOT NULL,
	"OCCURRED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL
);

COMMENT ON COLUMN "STOCK_MOVEMENT"."MOVEMENT_ID" IS '재고 변동 이력을 식별하는 ID';

COMMENT ON COLUMN "STOCK_MOVEMENT"."SALE_ID" IS '재고 변동의 원인인 판매를 참조하는 ID';

COMMENT ON COLUMN "STOCK_MOVEMENT"."SALE_LINE_ID" IS '원인 판매에 속한 품목 행을 참조하는 ID';

COMMENT ON COLUMN "STOCK_MOVEMENT"."WAREHOUSE_ID" IS '창고 ID';

COMMENT ON COLUMN "STOCK_MOVEMENT"."ITEM_ID" IS '품목 ID';

COMMENT ON COLUMN "STOCK_MOVEMENT"."QUANTITY_DELTA" IS '재고 증감량(+: 증가, -: 감소)';

COMMENT ON COLUMN "STOCK_MOVEMENT"."OCCURRED_AT" IS '재고 증감을 처리한 시각';

CREATE TABLE "BIZ_PARTNER" (
	"PARTNER_ID"	NUMBER(18,0)		NOT NULL,
	"PARTNER_CODE"	VARCHAR2(30 CHAR)		NOT NULL,
	"PARTNER_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"BUSINESS_NO"	VARCHAR2(20 CHAR)		NULL,
	"REPRESENTATIVE"	VARCHAR2(100 CHAR)		NULL,
	"BUSINESS_TYPE"	VARCHAR2(100 CHAR)		NULL,
	"BUSINESS_ITEM"	VARCHAR2(100 CHAR)		NULL,
	"PHONE"	VARCHAR2(30 CHAR)		NULL,
	"MOBILE"	VARCHAR2(30 CHAR)		NULL,
	"EMAIL"	VARCHAR2(254 CHAR)		NULL,
	"POSTAL_CODE"	VARCHAR2(20 CHAR)		NULL,
	"ADDRESS"	VARCHAR2(300 CHAR)		NULL,
	"ASSIGNEE_ID"	NUMBER(18,0)		NULL,
	"ASSIGNEE_NAME"	VARCHAR2(100 CHAR)		NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"UPDATED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL,
	"ACTIVE_FLAG"	VARCHAR2(1 CHAR)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "BIZ_PARTNER"."PARTNER_ID" IS '거래처 ID';

COMMENT ON COLUMN "BIZ_PARTNER"."PARTNER_CODE" IS '거래처 코드';

COMMENT ON COLUMN "BIZ_PARTNER"."PARTNER_NAME" IS '상호';

COMMENT ON COLUMN "BIZ_PARTNER"."BUSINESS_NO" IS '사업자등록번호';

COMMENT ON COLUMN "BIZ_PARTNER"."REPRESENTATIVE" IS '거래처를 대표하는 사람의 이름';

COMMENT ON COLUMN "BIZ_PARTNER"."BUSINESS_TYPE" IS '사업자 업태';

COMMENT ON COLUMN "BIZ_PARTNER"."BUSINESS_ITEM" IS '사업자 종목';

COMMENT ON COLUMN "BIZ_PARTNER"."PHONE" IS '거래처 전화번호';

COMMENT ON COLUMN "BIZ_PARTNER"."MOBILE" IS '거래처 휴대전화번호';

COMMENT ON COLUMN "BIZ_PARTNER"."EMAIL" IS '거래처에 연락할 이메일 주소';

COMMENT ON COLUMN "BIZ_PARTNER"."POSTAL_CODE" IS '거래처 주소에 해당하는 우편번호';

COMMENT ON COLUMN "BIZ_PARTNER"."ADDRESS" IS '거래처가 위치한 주소';

COMMENT ON COLUMN "BIZ_PARTNER"."ASSIGNEE_ID" IS '담당자를 식별하는 ID';

COMMENT ON COLUMN "BIZ_PARTNER"."ASSIGNEE_NAME" IS '담당자명';

COMMENT ON COLUMN "BIZ_PARTNER"."NOTE" IS '거래처에 대한 참고 내용';

COMMENT ON COLUMN "BIZ_PARTNER"."UPDATED_AT" IS '마지막으로 변경한 시각';

COMMENT ON COLUMN "BIZ_PARTNER"."ACTIVE_FLAG" IS 'Y: 사용, N: 사용 중단, 기본값: Y';

CREATE TABLE "SALES_ORDER_LINE" (
	"SALES_ORDER_LINE_ID"	NUMBER(18,0)		NOT NULL,
	"SALES_ORDER_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"SPECIFICATION"	VARCHAR2(100 CHAR)		NULL,
	"UNIT"	VARCHAR2(20 CHAR)		NULL,
	"QUANTITY"	NUMBER(18,3)		NOT NULL,
	"UNIT_PRICE"	NUMBER(18,2)		NOT NULL,
	"SUPPLY_AMOUNT"	NUMBER(18,0)		NOT NULL,
	"VAT_AMOUNT"	NUMBER(18,0)		NOT NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"TOTAL_AMOUNT"	NUMBER(18,0)		NOT NULL,
	"DELETED_YN"	VARCHAR2(1 CHAR)	DEFAULT 'N'	NOT NULL,
	"QUOTATION_LINE_ID"	NUMBER(18,0)		NULL
);

COMMENT ON COLUMN "SALES_ORDER_LINE"."SALES_ORDER_LINE_ID" IS '주문서 품목 행을 식별하는 ID';

COMMENT ON COLUMN "SALES_ORDER_LINE"."SALES_ORDER_ID" IS '이 행이 속한 주문서를 참조하는 ID';

COMMENT ON COLUMN "SALES_ORDER_LINE"."ITEM_ID" IS '연결된 품목을 식별하는 ID';

COMMENT ON COLUMN "SALES_ORDER_LINE"."ITEM_NAME" IS '행에 보존한 당시 품목 이름';

COMMENT ON COLUMN "SALES_ORDER_LINE"."SPECIFICATION" IS '행에 보존한 당시 품목 규격';

COMMENT ON COLUMN "SALES_ORDER_LINE"."UNIT" IS '거래 당시 품목의 수량 단위';

COMMENT ON COLUMN "SALES_ORDER_LINE"."QUANTITY" IS '입력한 품목 수량';

COMMENT ON COLUMN "SALES_ORDER_LINE"."UNIT_PRICE" IS '품목의 출고단가';

COMMENT ON COLUMN "SALES_ORDER_LINE"."SUPPLY_AMOUNT" IS '수량×단가, 원 단위로 반올림';

COMMENT ON COLUMN "SALES_ORDER_LINE"."VAT_AMOUNT" IS '공급가액×10%, 원 단위로 반올림';

COMMENT ON COLUMN "SALES_ORDER_LINE"."NOTE" IS '주문서 상세행 비고';

COMMENT ON COLUMN "SALES_ORDER_LINE"."TOTAL_AMOUNT" IS '공급가액과 부가세액을 합한 금액';

COMMENT ON COLUMN "SALES_ORDER_LINE"."DELETED_YN" IS '삭제 시: Y, 기본값: N';

COMMENT ON COLUMN "SALES_ORDER_LINE"."QUOTATION_LINE_ID" IS '원견적서의 품목 행을 참조하는 ID';

CREATE TABLE "ITEM" (
	"ITEM_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_CODE"	VARCHAR2(30 CHAR)		NOT NULL,
	"ITEM_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"SPECIFICATION"	VARCHAR2(100 CHAR)		NULL,
	"UNIT"	VARCHAR2(20 CHAR)		NULL,
	"ITEM_TYPE"	VARCHAR2(20 CHAR)		NOT NULL,
	"INBOUND_PRICE"	NUMBER(18,2)	DEFAULT 0	NOT NULL,
	"OUTBOUND_PRICE"	NUMBER(18,2)	DEFAULT 0	NOT NULL,
	"IMAGE_PATH"	VARCHAR2(500 CHAR)		NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"UPDATED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL,
	"ACTIVE_FLAG"	VARCHAR2(1 CHAR)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "ITEM"."ITEM_ID" IS '품목 ID';

COMMENT ON COLUMN "ITEM"."ITEM_CODE" IS '품목 코드';

COMMENT ON COLUMN "ITEM"."ITEM_NAME" IS '현재 등록된 품목 이름';

COMMENT ON COLUMN "ITEM"."SPECIFICATION" IS '품목의 크기나 형태를 나타내는 규격';

COMMENT ON COLUMN "ITEM"."UNIT" IS '품목 수량을 세는 단위';

COMMENT ON COLUMN "ITEM"."ITEM_TYPE" IS '품목의 구분. 원재료·부재료·제품·반제품·상품·무형상품 중 선택';

COMMENT ON COLUMN "ITEM"."INBOUND_PRICE" IS '입고단가, 기본값: 0';

COMMENT ON COLUMN "ITEM"."OUTBOUND_PRICE" IS '출고단가. 견적서·주문서·판매에서 단가 초기값으로 사용, 기본값: 0';

COMMENT ON COLUMN "ITEM"."IMAGE_PATH" IS '대표 사진의 업로드 폴더 기준 상대 경로';

COMMENT ON COLUMN "ITEM"."NOTE" IS '품목에 대한 참고 내용';

COMMENT ON COLUMN "ITEM"."UPDATED_AT" IS '마지막으로 변경한 시각';

COMMENT ON COLUMN "ITEM"."ACTIVE_FLAG" IS 'Y: 사용, N: 사용 중단, 기본값: Y';

CREATE TABLE "QUOTATION_LINE" (
	"QUOTATION_LINE_ID"	NUMBER(18,0)		NOT NULL,
	"QUOTATION_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"SPECIFICATION"	VARCHAR2(100 CHAR)		NULL,
	"UNIT"	VARCHAR2(20 CHAR)		NULL,
	"QUANTITY"	NUMBER(18,3)		NOT NULL,
	"UNIT_PRICE"	NUMBER(18,2)		NOT NULL,
	"SUPPLY_AMOUNT"	NUMBER(18,0)		NOT NULL,
	"VAT_AMOUNT"	NUMBER(18,0)		NOT NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"TOTAL_AMOUNT"	NUMBER(18,0)		NOT NULL,
	"DELETED_YN"	VARCHAR2(1 CHAR)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "QUOTATION_LINE"."QUOTATION_LINE_ID" IS '견적서 품목 행을 식별하는 ID';

COMMENT ON COLUMN "QUOTATION_LINE"."QUOTATION_ID" IS '이 행이 속한 견적서를 참조하는 ID';

COMMENT ON COLUMN "QUOTATION_LINE"."ITEM_ID" IS '연결된 품목을 식별하는 ID';

COMMENT ON COLUMN "QUOTATION_LINE"."ITEM_NAME" IS '행에 보존한 당시 품목 이름';

COMMENT ON COLUMN "QUOTATION_LINE"."SPECIFICATION" IS '행에 보존한 당시 품목 규격';

COMMENT ON COLUMN "QUOTATION_LINE"."UNIT" IS '거래 당시 품목의 수량 단위';

COMMENT ON COLUMN "QUOTATION_LINE"."QUANTITY" IS '입력한 품목 수량';

COMMENT ON COLUMN "QUOTATION_LINE"."UNIT_PRICE" IS '품목의 출고단가';

COMMENT ON COLUMN "QUOTATION_LINE"."SUPPLY_AMOUNT" IS '수량×단가, 원 단위로 반올림';

COMMENT ON COLUMN "QUOTATION_LINE"."VAT_AMOUNT" IS '공급가액×10%, 원 단위로 반올림';

COMMENT ON COLUMN "QUOTATION_LINE"."NOTE" IS '견적서 상세행 비고';

COMMENT ON COLUMN "QUOTATION_LINE"."TOTAL_AMOUNT" IS '공급가액과 부가세액을 합한 금액';

COMMENT ON COLUMN "QUOTATION_LINE"."DELETED_YN" IS '삭제 시: Y, 기본값: N';

CREATE TABLE "STOCK" (
	"WAREHOUSE_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_ID"	NUMBER(18,0)		NOT NULL,
	"QUANTITY"	NUMBER(18,3)	DEFAULT 0	NOT NULL,
	"UPDATED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL
);

COMMENT ON COLUMN "STOCK"."WAREHOUSE_ID" IS '창고 ID';

COMMENT ON COLUMN "STOCK"."ITEM_ID" IS '품목 ID';

COMMENT ON COLUMN "STOCK"."QUANTITY" IS '재고수량 , 기본값: 0';

COMMENT ON COLUMN "STOCK"."UPDATED_AT" IS '마지막으로 변경한 시각';

CREATE TABLE "SALE" (
	"SALE_ID"	NUMBER(18,0)		NOT NULL,
	"SALE_NO"	VARCHAR2(30 CHAR)		NOT NULL,
	"BUSINESS_DATE"	DATE		NOT NULL,
	"PARTNER_ID"	NUMBER(18,0)		NULL,
	"PARTNER_NAME"	VARCHAR2(100 CHAR)		NULL,
	"WAREHOUSE_ID"	NUMBER(18,0)		NOT NULL,
	"WAREHOUSE_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"ASSIGNEE_ID"	NUMBER(18,0)		NULL,
	"ASSIGNEE_NAME"	VARCHAR2(100 CHAR)		NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"PROGRESS_STATUS"	VARCHAR2(20 CHAR)	DEFAULT 'CONFIRMED'	NOT NULL,
	"CREATED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL,
	"UPDATED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL,
	"DELETED_YN"	VARCHAR2(1 CHAR)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "SALE"."SALE_ID" IS '판매를 식별하는 ID';

COMMENT ON COLUMN "SALE"."SALE_NO" IS '판매 번호';

COMMENT ON COLUMN "SALE"."BUSINESS_DATE" IS '판매 업무 기준 날짜';

COMMENT ON COLUMN "SALE"."PARTNER_ID" IS '연결된 거래처를 식별하는 ID';

COMMENT ON COLUMN "SALE"."PARTNER_NAME" IS '전표에 보존한 당시 거래처 이름';

COMMENT ON COLUMN "SALE"."WAREHOUSE_ID" IS '연결된 창고를 식별하는 ID';

COMMENT ON COLUMN "SALE"."WAREHOUSE_NAME" IS '전표에 보존한 당시 창고 이름';

COMMENT ON COLUMN "SALE"."ASSIGNEE_ID" IS '선택한 담당자를 참조하는 ID';

COMMENT ON COLUMN "SALE"."ASSIGNEE_NAME" IS '전표에 보존한 당시 담당자명';

COMMENT ON COLUMN "SALE"."NOTE" IS '전표에 남기는 참고 내용';

COMMENT ON COLUMN "SALE"."PROGRESS_STATUS" IS 'UNCONFIRMED: 미확인, CONFIRMED: 확인, 기본값: CONFIRMED';

COMMENT ON COLUMN "SALE"."CREATED_AT" IS '처음 저장한 시각';

COMMENT ON COLUMN "SALE"."UPDATED_AT" IS '마지막으로 변경한 시각';

COMMENT ON COLUMN "SALE"."DELETED_YN" IS '삭제 시: Y, 기본값: N';

CREATE TABLE "SALE_LINE" (
	"SALE_LINE_ID"	NUMBER(18,0)		NOT NULL,
	"SALE_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"SPECIFICATION"	VARCHAR2(100 CHAR)		NULL,
	"UNIT"	VARCHAR2(20 CHAR)		NULL,
	"QUANTITY"	NUMBER(18,3)		NOT NULL,
	"UNIT_PRICE"	NUMBER(18,2)		NOT NULL,
	"SUPPLY_AMOUNT"	NUMBER(18,0)		NOT NULL,
	"VAT_AMOUNT"	NUMBER(18,0)		NOT NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"TOTAL_AMOUNT"	NUMBER(18,0)		NOT NULL,
	"DELETED_YN"	VARCHAR2(1 CHAR)	DEFAULT 'N'	NOT NULL,
	"SALES_ORDER_LINE_ID"	NUMBER(18,0)		NULL
);

COMMENT ON COLUMN "SALE_LINE"."SALE_LINE_ID" IS '판매 품목 행을 식별하는 ID';

COMMENT ON COLUMN "SALE_LINE"."SALE_ID" IS '이 행이 속한 판매를 참조하는 ID';

COMMENT ON COLUMN "SALE_LINE"."ITEM_ID" IS '연결된 품목을 식별하는 ID';

COMMENT ON COLUMN "SALE_LINE"."ITEM_NAME" IS '행에 보존한 당시 품목 이름';

COMMENT ON COLUMN "SALE_LINE"."SPECIFICATION" IS '행에 보존한 당시 품목 규격';

COMMENT ON COLUMN "SALE_LINE"."UNIT" IS '거래 당시 품목의 수량 단위';

COMMENT ON COLUMN "SALE_LINE"."QUANTITY" IS '입력한 품목 수량';

COMMENT ON COLUMN "SALE_LINE"."UNIT_PRICE" IS '품목의 출고단가';

COMMENT ON COLUMN "SALE_LINE"."SUPPLY_AMOUNT" IS '수량×단가, 원 단위로 반올림';

COMMENT ON COLUMN "SALE_LINE"."VAT_AMOUNT" IS '공급가액×10%, 원 단위로 반올림';

COMMENT ON COLUMN "SALE_LINE"."NOTE" IS '판매 상세행 비고';

COMMENT ON COLUMN "SALE_LINE"."TOTAL_AMOUNT" IS '공급가액과 부가세액을 합한 금액';

COMMENT ON COLUMN "SALE_LINE"."DELETED_YN" IS '삭제 시: Y, 기본값: N';

COMMENT ON COLUMN "SALE_LINE"."SALES_ORDER_LINE_ID" IS '원주문서의 품목 행을 참조하는 ID';

CREATE TABLE "SHIP_INSTRUCTION_LINE" (
	"SHIP_INSTRUCTION_LINE_ID"	NUMBER(18,0)		NOT NULL,
	"SHIP_INSTRUCTION_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_ID"	NUMBER(18,0)		NOT NULL,
	"ITEM_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"SPECIFICATION"	VARCHAR2(100 CHAR)		NULL,
	"UNIT"	VARCHAR2(20 CHAR)		NULL,
	"QUANTITY"	NUMBER(18,3)		NOT NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"DELETED_YN"	VARCHAR2(1 CHAR)	DEFAULT 'N'	NOT NULL,
	"SALE_LINE_ID"	NUMBER(18,0)		NULL
);

COMMENT ON COLUMN "SHIP_INSTRUCTION_LINE"."SHIP_INSTRUCTION_LINE_ID" IS '출하지시서 품목 행을 식별하는 ID';

COMMENT ON COLUMN "SHIP_INSTRUCTION_LINE"."SHIP_INSTRUCTION_ID" IS '이 행이 속한 출하지시서를 참조하는 ID';

COMMENT ON COLUMN "SHIP_INSTRUCTION_LINE"."ITEM_ID" IS '연결된 품목을 식별하는 ID';

COMMENT ON COLUMN "SHIP_INSTRUCTION_LINE"."ITEM_NAME" IS '행에 보존한 당시 품목 이름';

COMMENT ON COLUMN "SHIP_INSTRUCTION_LINE"."SPECIFICATION" IS '행에 보존한 당시 품목 규격';

COMMENT ON COLUMN "SHIP_INSTRUCTION_LINE"."UNIT" IS '거래 당시 품목의 수량 단위';

COMMENT ON COLUMN "SHIP_INSTRUCTION_LINE"."QUANTITY" IS '입력한 품목 수량';

COMMENT ON COLUMN "SHIP_INSTRUCTION_LINE"."NOTE" IS '출하지시서 상세행 비고';

COMMENT ON COLUMN "SHIP_INSTRUCTION_LINE"."DELETED_YN" IS '삭제 시: Y, 기본값: N';

COMMENT ON COLUMN "SHIP_INSTRUCTION_LINE"."SALE_LINE_ID" IS '원판매의 품목 행을 참조하는 ID';

CREATE TABLE "ASSIGNEE" (
	"ASSIGNEE_ID"	NUMBER(18,0)		NOT NULL,
	"ASSIGNEE_CODE"	VARCHAR2(30 CHAR)		NOT NULL,
	"ASSIGNEE_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"ACTIVE_FLAG"	VARCHAR2(1 CHAR)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "ASSIGNEE"."ASSIGNEE_ID" IS '담당자를 식별하는 ID';

COMMENT ON COLUMN "ASSIGNEE"."ASSIGNEE_CODE" IS '담당자 코드';

COMMENT ON COLUMN "ASSIGNEE"."ASSIGNEE_NAME" IS '선택 목록에 표시할 담당자 이름';

COMMENT ON COLUMN "ASSIGNEE"."ACTIVE_FLAG" IS 'Y: 사용, N: 사용 중단, 기본값: Y';

CREATE TABLE "SHIP_INSTRUCTION" (
	"SHIP_INSTRUCTION_ID"	NUMBER(18,0)		NOT NULL,
	"SHIP_INSTRUCTION_NO"	VARCHAR2(30 CHAR)		NOT NULL,
	"BUSINESS_DATE"	DATE		NOT NULL,
	"PARTNER_ID"	NUMBER(18,0)		NULL,
	"PARTNER_NAME"	VARCHAR2(100 CHAR)		NULL,
	"WAREHOUSE_ID"	NUMBER(18,0)		NOT NULL,
	"WAREHOUSE_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"ASSIGNEE_ID"	NUMBER(18,0)		NULL,
	"ASSIGNEE_NAME"	VARCHAR2(100 CHAR)		NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"PLANNED_DATE"	DATE		NULL,
	"DELIVERY_CONTACT"	VARCHAR2(30 CHAR)		NULL,
	"DELIVERY_POSTAL_CODE"	VARCHAR2(20 CHAR)		NULL,
	"DELIVERY_ADDRESS"	VARCHAR2(300 CHAR)		NULL,
	"PROGRESS_STATUS"	VARCHAR2(20 CHAR)	DEFAULT 'IN_PROGRESS'	NOT NULL,
	"UPDATED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL,
	"DELETED_YN"	VARCHAR2(1 CHAR)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "SHIP_INSTRUCTION"."SHIP_INSTRUCTION_ID" IS '출하지시서를 식별하는 ID';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."SHIP_INSTRUCTION_NO" IS '출하지시서 번호';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."BUSINESS_DATE" IS '출하지시 업무 기준 날짜';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."PARTNER_ID" IS '연결된 거래처를 식별하는 ID';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."PARTNER_NAME" IS '전표에 보존한 당시 거래처 이름';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."WAREHOUSE_ID" IS '연결된 창고를 식별하는 ID';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."WAREHOUSE_NAME" IS '전표에 보존한 당시 창고 이름';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."ASSIGNEE_ID" IS '선택한 담당자를 참조하는 ID';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."ASSIGNEE_NAME" IS '전표에 보존한 당시 담당자명';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."NOTE" IS '전표에 남기는 참고 내용';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."PLANNED_DATE" IS '출하하기로 예정한 날짜';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."DELIVERY_CONTACT" IS '전표에 저장한 배송지 연락처';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."DELIVERY_POSTAL_CODE" IS '전표에 저장한 배송지 우편번호';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."DELIVERY_ADDRESS" IS '전표에 저장한 배송지 주소';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."PROGRESS_STATUS" IS 'IN_PROGRESS: 진행중, COMPLETED: 완료, 기본값: IN_PROGRESS';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."UPDATED_AT" IS '마지막으로 변경한 시각';

COMMENT ON COLUMN "SHIP_INSTRUCTION"."DELETED_YN" IS '삭제 시: Y, 기본값: N';

CREATE TABLE "WAREHOUSE" (
	"WAREHOUSE_ID"	NUMBER(18,0)		NOT NULL,
	"WAREHOUSE_CODE"	VARCHAR2(30 CHAR)		NOT NULL,
	"WAREHOUSE_NAME"	VARCHAR2(100 CHAR)		NOT NULL,
	"WAREHOUSE_TYPE"	VARCHAR2(10 CHAR)		NOT NULL,
	"UPDATED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL,
	"ACTIVE_FLAG"	VARCHAR2(1 CHAR)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "WAREHOUSE"."WAREHOUSE_ID" IS '창고 ID';

COMMENT ON COLUMN "WAREHOUSE"."WAREHOUSE_CODE" IS '창고 코드';

COMMENT ON COLUMN "WAREHOUSE"."WAREHOUSE_NAME" IS '현재 등록된 창고 이름';

COMMENT ON COLUMN "WAREHOUSE"."WAREHOUSE_TYPE" IS '창고 또는 공장 중 선택';

COMMENT ON COLUMN "WAREHOUSE"."UPDATED_AT" IS '마지막으로 변경한 시각';

COMMENT ON COLUMN "WAREHOUSE"."ACTIVE_FLAG" IS 'Y: 사용, N: 사용 중단, 기본값: Y';

CREATE TABLE "QUOTATION" (
	"QUOTATION_ID"	NUMBER(18,0)		NOT NULL,
	"QUOTATION_NO"	VARCHAR2(30 CHAR)		NOT NULL,
	"BUSINESS_DATE"	DATE		NOT NULL,
	"PARTNER_ID"	NUMBER(18,0)		NULL,
	"PARTNER_NAME"	VARCHAR2(100 CHAR)		NULL,
	"WAREHOUSE_ID"	NUMBER(18,0)		NULL,
	"WAREHOUSE_NAME"	VARCHAR2(100 CHAR)		NULL,
	"ASSIGNEE_ID"	NUMBER(18,0)		NULL,
	"ASSIGNEE_NAME"	VARCHAR2(100 CHAR)		NULL,
	"NOTE"	VARCHAR2(500 CHAR)		NULL,
	"PROGRESS_STATUS"	VARCHAR2(20 CHAR)	DEFAULT 'IN_PROGRESS'	NOT NULL,
	"UPDATED_AT"	TIMESTAMP(6)	DEFAULT LOCALTIMESTAMP	NOT NULL,
	"DELETED_YN"	VARCHAR2(1 CHAR)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "QUOTATION"."QUOTATION_ID" IS '견적서를 식별하는 ID';

COMMENT ON COLUMN "QUOTATION"."QUOTATION_NO" IS '견적서 번호';

COMMENT ON COLUMN "QUOTATION"."BUSINESS_DATE" IS '견적 업무 기준 날짜';

COMMENT ON COLUMN "QUOTATION"."PARTNER_ID" IS '연결된 거래처를 식별하는 ID';

COMMENT ON COLUMN "QUOTATION"."PARTNER_NAME" IS '전표에 보존한 당시 거래처 이름';

COMMENT ON COLUMN "QUOTATION"."WAREHOUSE_ID" IS '연결된 창고를 식별하는 ID';

COMMENT ON COLUMN "QUOTATION"."WAREHOUSE_NAME" IS '전표에 보존한 당시 창고 이름';

COMMENT ON COLUMN "QUOTATION"."ASSIGNEE_ID" IS '선택한 담당자를 참조하는 ID';

COMMENT ON COLUMN "QUOTATION"."ASSIGNEE_NAME" IS '전표에 보존한 당시 담당자명';

COMMENT ON COLUMN "QUOTATION"."NOTE" IS '전표에 남기는 참고 내용';

COMMENT ON COLUMN "QUOTATION"."PROGRESS_STATUS" IS 'UNCONFIRMED: 미확인, IN_PROGRESS: 진행중, COMPLETED: 완료, 기본값: IN_PROGRESS';

COMMENT ON COLUMN "QUOTATION"."UPDATED_AT" IS '마지막으로 변경한 시각';

COMMENT ON COLUMN "QUOTATION"."DELETED_YN" IS '삭제 시: Y, 기본값: N';

ALTER TABLE "SALES_ORDER" 
ADD CONSTRAINT "PK_SALES_ORDER" 
PRIMARY KEY ("SALES_ORDER_ID");

ALTER TABLE "SHIPMENT_LINE" 
ADD CONSTRAINT "PK_SHIPMENT_LINE" 
PRIMARY KEY ("SHIPMENT_LINE_ID");

ALTER TABLE "SHIPMENT" 
ADD CONSTRAINT "PK_SHIPMENT" 
PRIMARY KEY ("SHIPMENT_ID");

ALTER TABLE "STOCK_MOVEMENT" 
ADD CONSTRAINT "PK_STOCK_MOVEMENT" 
PRIMARY KEY ("MOVEMENT_ID");

ALTER TABLE "BIZ_PARTNER" 
ADD CONSTRAINT "PK_BIZ_PARTNER" 
PRIMARY KEY ("PARTNER_ID");

ALTER TABLE "SALES_ORDER_LINE" 
ADD CONSTRAINT "PK_SALES_ORDER_LINE" 
PRIMARY KEY ("SALES_ORDER_LINE_ID");

ALTER TABLE "ITEM" 
ADD CONSTRAINT "PK_ITEM" 
PRIMARY KEY ("ITEM_ID");

ALTER TABLE "QUOTATION_LINE" 
ADD CONSTRAINT "PK_QUOTATION_LINE" 
PRIMARY KEY ("QUOTATION_LINE_ID");

ALTER TABLE "STOCK" 
ADD CONSTRAINT "PK_STOCK" 
PRIMARY KEY ("WAREHOUSE_ID", "ITEM_ID");

ALTER TABLE "SALE" 
ADD CONSTRAINT "PK_SALE" 
PRIMARY KEY ("SALE_ID");

ALTER TABLE "SALE_LINE" 
ADD CONSTRAINT "PK_SALE_LINE" 
PRIMARY KEY ("SALE_LINE_ID");

ALTER TABLE "SHIP_INSTRUCTION_LINE" 
ADD CONSTRAINT "PK_SHIP_INSTRUCTION_LINE" 
PRIMARY KEY ("SHIP_INSTRUCTION_LINE_ID");

ALTER TABLE "ASSIGNEE" 
ADD CONSTRAINT "PK_ASSIGNEE" 
PRIMARY KEY ("ASSIGNEE_ID");

ALTER TABLE "SHIP_INSTRUCTION" 
ADD CONSTRAINT "PK_SHIP_INSTRUCTION" 
PRIMARY KEY ("SHIP_INSTRUCTION_ID");

ALTER TABLE "WAREHOUSE" 
ADD CONSTRAINT "PK_WAREHOUSE" 
PRIMARY KEY ("WAREHOUSE_ID");

ALTER TABLE "QUOTATION" 
ADD CONSTRAINT "PK_QUOTATION" 
PRIMARY KEY ("QUOTATION_ID");

ALTER TABLE "SALES_ORDER"
ADD CONSTRAINT "FK_SO_PARTNER"
FOREIGN KEY ("PARTNER_ID")
REFERENCES "BIZ_PARTNER" ("PARTNER_ID");

ALTER TABLE "SALES_ORDER"
ADD CONSTRAINT "FK_SO_WAREHOUSE"
FOREIGN KEY ("WAREHOUSE_ID")
REFERENCES "WAREHOUSE" ("WAREHOUSE_ID");

ALTER TABLE "SALES_ORDER"
ADD CONSTRAINT "FK_SO_ASSIGNEE"
FOREIGN KEY ("ASSIGNEE_ID")
REFERENCES "ASSIGNEE" ("ASSIGNEE_ID");


ALTER TABLE "SHIPMENT_LINE"
ADD CONSTRAINT "FK_SHL_SHIPMENT"
FOREIGN KEY ("SHIPMENT_ID")
REFERENCES "SHIPMENT" ("SHIPMENT_ID");

ALTER TABLE "SHIPMENT_LINE"
ADD CONSTRAINT "FK_SHL_ITEM"
FOREIGN KEY ("ITEM_ID")
REFERENCES "ITEM" ("ITEM_ID");

ALTER TABLE "SHIPMENT_LINE"
ADD CONSTRAINT "FK_SHL_INST_LINE"
FOREIGN KEY ("SHIP_INSTRUCTION_LINE_ID")
REFERENCES "SHIP_INSTRUCTION_LINE" ("SHIP_INSTRUCTION_LINE_ID");


ALTER TABLE "SHIPMENT"
ADD CONSTRAINT "FK_SH_PARTNER"
FOREIGN KEY ("PARTNER_ID")
REFERENCES "BIZ_PARTNER" ("PARTNER_ID");

ALTER TABLE "SHIPMENT"
ADD CONSTRAINT "FK_SH_WAREHOUSE"
FOREIGN KEY ("WAREHOUSE_ID")
REFERENCES "WAREHOUSE" ("WAREHOUSE_ID");

ALTER TABLE "SHIPMENT"
ADD CONSTRAINT "FK_SH_ASSIGNEE"
FOREIGN KEY ("ASSIGNEE_ID")
REFERENCES "ASSIGNEE" ("ASSIGNEE_ID");


ALTER TABLE "STOCK_MOVEMENT"
ADD CONSTRAINT "FK_SM_SALE"
FOREIGN KEY ("SALE_ID")
REFERENCES "SALE" ("SALE_ID");

ALTER TABLE "STOCK_MOVEMENT"
ADD CONSTRAINT "FK_SM_SALE_LINE"
FOREIGN KEY ("SALE_LINE_ID")
REFERENCES "SALE_LINE" ("SALE_LINE_ID");

ALTER TABLE "STOCK_MOVEMENT"
ADD CONSTRAINT "FK_SM_STOCK"
FOREIGN KEY ("WAREHOUSE_ID", "ITEM_ID")
REFERENCES "STOCK" ("WAREHOUSE_ID", "ITEM_ID");


ALTER TABLE "BIZ_PARTNER"
ADD CONSTRAINT "FK_BP_ASSIGNEE"
FOREIGN KEY ("ASSIGNEE_ID")
REFERENCES "ASSIGNEE" ("ASSIGNEE_ID");


ALTER TABLE "SALES_ORDER_LINE"
ADD CONSTRAINT "FK_SOL_ORDER"
FOREIGN KEY ("SALES_ORDER_ID")
REFERENCES "SALES_ORDER" ("SALES_ORDER_ID");

ALTER TABLE "SALES_ORDER_LINE"
ADD CONSTRAINT "FK_SOL_ITEM"
FOREIGN KEY ("ITEM_ID")
REFERENCES "ITEM" ("ITEM_ID");

ALTER TABLE "SALES_ORDER_LINE"
ADD CONSTRAINT "FK_SOL_QUOTE_LINE"
FOREIGN KEY ("QUOTATION_LINE_ID")
REFERENCES "QUOTATION_LINE" ("QUOTATION_LINE_ID");


ALTER TABLE "QUOTATION_LINE"
ADD CONSTRAINT "FK_QTL_QUOTATION"
FOREIGN KEY ("QUOTATION_ID")
REFERENCES "QUOTATION" ("QUOTATION_ID");

ALTER TABLE "QUOTATION_LINE"
ADD CONSTRAINT "FK_QTL_ITEM"
FOREIGN KEY ("ITEM_ID")
REFERENCES "ITEM" ("ITEM_ID");


ALTER TABLE "STOCK"
ADD CONSTRAINT "FK_ST_WAREHOUSE"
FOREIGN KEY ("WAREHOUSE_ID")
REFERENCES "WAREHOUSE" ("WAREHOUSE_ID");

ALTER TABLE "STOCK"
ADD CONSTRAINT "FK_ST_ITEM"
FOREIGN KEY ("ITEM_ID")
REFERENCES "ITEM" ("ITEM_ID");


ALTER TABLE "SALE"
ADD CONSTRAINT "FK_SA_PARTNER"
FOREIGN KEY ("PARTNER_ID")
REFERENCES "BIZ_PARTNER" ("PARTNER_ID");

ALTER TABLE "SALE"
ADD CONSTRAINT "FK_SA_WAREHOUSE"
FOREIGN KEY ("WAREHOUSE_ID")
REFERENCES "WAREHOUSE" ("WAREHOUSE_ID");

ALTER TABLE "SALE"
ADD CONSTRAINT "FK_SA_ASSIGNEE"
FOREIGN KEY ("ASSIGNEE_ID")
REFERENCES "ASSIGNEE" ("ASSIGNEE_ID");


ALTER TABLE "SALE_LINE"
ADD CONSTRAINT "FK_SAL_SALE"
FOREIGN KEY ("SALE_ID")
REFERENCES "SALE" ("SALE_ID");

ALTER TABLE "SALE_LINE"
ADD CONSTRAINT "FK_SAL_ITEM"
FOREIGN KEY ("ITEM_ID")
REFERENCES "ITEM" ("ITEM_ID");

ALTER TABLE "SALE_LINE"
ADD CONSTRAINT "FK_SAL_ORDER_LINE"
FOREIGN KEY ("SALES_ORDER_LINE_ID")
REFERENCES "SALES_ORDER_LINE" ("SALES_ORDER_LINE_ID");


ALTER TABLE "SHIP_INSTRUCTION_LINE"
ADD CONSTRAINT "FK_SIL_SHIP_INST"
FOREIGN KEY ("SHIP_INSTRUCTION_ID")
REFERENCES "SHIP_INSTRUCTION" ("SHIP_INSTRUCTION_ID");

ALTER TABLE "SHIP_INSTRUCTION_LINE"
ADD CONSTRAINT "FK_SIL_ITEM"
FOREIGN KEY ("ITEM_ID")
REFERENCES "ITEM" ("ITEM_ID");

ALTER TABLE "SHIP_INSTRUCTION_LINE"
ADD CONSTRAINT "FK_SIL_SALE_LINE"
FOREIGN KEY ("SALE_LINE_ID")
REFERENCES "SALE_LINE" ("SALE_LINE_ID");


ALTER TABLE "SHIP_INSTRUCTION"
ADD CONSTRAINT "FK_SI_PARTNER"
FOREIGN KEY ("PARTNER_ID")
REFERENCES "BIZ_PARTNER" ("PARTNER_ID");

ALTER TABLE "SHIP_INSTRUCTION"
ADD CONSTRAINT "FK_SI_WAREHOUSE"
FOREIGN KEY ("WAREHOUSE_ID")
REFERENCES "WAREHOUSE" ("WAREHOUSE_ID");

ALTER TABLE "SHIP_INSTRUCTION"
ADD CONSTRAINT "FK_SI_ASSIGNEE"
FOREIGN KEY ("ASSIGNEE_ID")
REFERENCES "ASSIGNEE" ("ASSIGNEE_ID");


ALTER TABLE "QUOTATION"
ADD CONSTRAINT "FK_QT_PARTNER"
FOREIGN KEY ("PARTNER_ID")
REFERENCES "BIZ_PARTNER" ("PARTNER_ID");

ALTER TABLE "QUOTATION"
ADD CONSTRAINT "FK_QT_WAREHOUSE"
FOREIGN KEY ("WAREHOUSE_ID")
REFERENCES "WAREHOUSE" ("WAREHOUSE_ID");

ALTER TABLE "QUOTATION"
ADD CONSTRAINT "FK_QT_ASSIGNEE"
FOREIGN KEY ("ASSIGNEE_ID")
REFERENCES "ASSIGNEE" ("ASSIGNEE_ID");

ALTER TABLE "ASSIGNEE"
ADD CONSTRAINT "UQ_ASSIGNEE_CODE"
UNIQUE ("ASSIGNEE_CODE");

ALTER TABLE "WAREHOUSE"
ADD CONSTRAINT "UQ_WAREHOUSE_CODE"
UNIQUE ("WAREHOUSE_CODE");

ALTER TABLE "ITEM"
ADD CONSTRAINT "UQ_ITEM_CODE"
UNIQUE ("ITEM_CODE");

ALTER TABLE "BIZ_PARTNER"
ADD CONSTRAINT "UQ_PARTNER_CODE"
UNIQUE ("PARTNER_CODE");

ALTER TABLE "QUOTATION"
ADD CONSTRAINT "UQ_QUOTATION_NO"
UNIQUE ("QUOTATION_NO");

ALTER TABLE "SALES_ORDER"
ADD CONSTRAINT "UQ_SALES_ORDER_NO"
UNIQUE ("SALES_ORDER_NO");

ALTER TABLE "SALE"
ADD CONSTRAINT "UQ_SALE_NO"
UNIQUE ("SALE_NO");

ALTER TABLE "SHIP_INSTRUCTION"
ADD CONSTRAINT "UQ_SHIP_INST_NO"
UNIQUE ("SHIP_INSTRUCTION_NO");

ALTER TABLE "SHIPMENT"
ADD CONSTRAINT "UQ_SHIPMENT_NO"
UNIQUE ("SHIPMENT_NO");

CREATE SEQUENCE SEQ_ASSIGNEE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_PARTNER START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_WAREHOUSE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_ITEM START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_QUOTATION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_SALES_ORDER START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_SALE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_SHIP_INST START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_SHIPMENT START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_QUOTATION_LINE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_SALES_ORDER_LINE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_SALE_LINE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_SHIP_INST_LINE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_SHIPMENT_LINE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE SEQ_STOCK_MOVEMENT START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;