-- ====================================================================
-- 03_seed.sql : 팀 공통 개발용 기준 데이터 (Oracle 11g)
-- ====================================================================
-- [시나리오 맵]
--  [1]  견적만     견적 00001 한빛상사    노트북 10, 모니터 5 / 주문 0
--  [2]  부분 주문  견적 00002 미래유통    모니터 10 > 주문 00001(4) + 주문 00003(2) / 미주문 4
--  [3]  전부 주문  견적 00003 대한전자    키보드 10 > 주문 00002(10) / 미주문 0
--  [4]  주문만     주문 00005 누리테크    노트북 거치대 10 / 판매 0
--  [5]  부분 판매  주문 00004 서울오피스  노트북 10 > 판매 00003(4) / 미판매 6
--  [6]  전부 판매  주문 00002 대한전자    키보드 10 > 판매 00001(6) + 판매 00002(4) / 미판매 0
--  [7]  판매       5건 9행 (키보드 단가 50,000 / 48,000 / 52,000, 마우스 20,000 / 19,000)
--  [8]  출하지시   판매 00001 > 출하지시 00001 (키보드 6 중 6, 마우스 5 중 3)
--                  판매 00003 > 출하지시 00002 (노트북 4 중 4)
--  [9]  출하       출하지시 00001 > 출하 00001 (키보드 6 중 4, 마우스 3 중 3)
--                  출하지시 00002 > 출하 00002 (노트북 4 중 4)
--  [10] 직접 입력  주문 00004 00005 00006, 판매 00004 00005 (+ 판매 00001 마우스 행),
--                  출하지시 00003, 출하 00003
--  미확인 상태     견적 00005, 주문 00006, 판매 00005, 출하 00003
--  삭제 데이터     견적 00004 (헤더와 상세 DELETED_YN = 'Y', 연결 전표 없음)
--  사용중단        거래처 00006, 창고 00004, 품목 00010 (전표와 재고 연결 없음)
-- ====================================================================

-- ====================================================================
-- 1. ASSIGNEE (담당자 3건)
-- ====================================================================

-- 00001 김철수
INSERT INTO ASSIGNEE (ASSIGNEE_ID, ASSIGNEE_CODE, ASSIGNEE_NAME, ACTIVE_FLAG)
SELECT SEQ_ASSIGNEE.NEXTVAL, LPAD(TO_CHAR(SEQ_ASSIGNEE.NEXTVAL), 5, '0'), '김철수', 'Y'
  FROM DUAL;

-- 00002 이영희
INSERT INTO ASSIGNEE (ASSIGNEE_ID, ASSIGNEE_CODE, ASSIGNEE_NAME, ACTIVE_FLAG)
SELECT SEQ_ASSIGNEE.NEXTVAL, LPAD(TO_CHAR(SEQ_ASSIGNEE.NEXTVAL), 5, '0'), '이영희', 'Y'
  FROM DUAL;

-- 00003 박민수
INSERT INTO ASSIGNEE (ASSIGNEE_ID, ASSIGNEE_CODE, ASSIGNEE_NAME, ACTIVE_FLAG)
SELECT SEQ_ASSIGNEE.NEXTVAL, LPAD(TO_CHAR(SEQ_ASSIGNEE.NEXTVAL), 5, '0'), '박민수', 'Y'
  FROM DUAL;

-- ====================================================================
-- 2. BIZ_PARTNER (거래처 6건 : 사용 5 + 사용중단 1)
--    ASSIGNEE_NAME은 참조하는 담당자 이름과 동일
-- ====================================================================

-- 00001 한빛상사 (담당 김철수)
INSERT INTO BIZ_PARTNER (PARTNER_ID, PARTNER_CODE, PARTNER_NAME, BUSINESS_NO, REPRESENTATIVE,
                         BUSINESS_TYPE, BUSINESS_ITEM, PHONE, MOBILE, EMAIL,
                         POSTAL_CODE, ADDRESS, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, ACTIVE_FLAG)
SELECT SEQ_PARTNER.NEXTVAL, LPAD(TO_CHAR(SEQ_PARTNER.NEXTVAL), 5, '0'), '한빛상사', '123-81-00001', '최민준',
       '도소매', '컴퓨터 및 주변기기', '02-1000-0001', '010-0000-0001', 'hanbit@example.com',
       '06241', '서울특별시 강남구 강남대로 320',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00001'), '김철수', NULL, 'Y'
  FROM DUAL;

-- 00002 미래유통 (담당 이영희)
INSERT INTO BIZ_PARTNER (PARTNER_ID, PARTNER_CODE, PARTNER_NAME, BUSINESS_NO, REPRESENTATIVE,
                         BUSINESS_TYPE, BUSINESS_ITEM, PHONE, MOBILE, EMAIL,
                         POSTAL_CODE, ADDRESS, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, ACTIVE_FLAG)
SELECT SEQ_PARTNER.NEXTVAL, LPAD(TO_CHAR(SEQ_PARTNER.NEXTVAL), 5, '0'), '미래유통', '123-81-00002', '강서연',
       '도매', '사무기기', '031-1000-0002', '010-0000-0002', 'mirae@example.com',
       '13494', '경기도 성남시 분당구 판교역로 100',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00002'), '이영희', NULL, 'Y'
  FROM DUAL;

-- 00003 대한전자 (담당 박민수)
INSERT INTO BIZ_PARTNER (PARTNER_ID, PARTNER_CODE, PARTNER_NAME, BUSINESS_NO, REPRESENTATIVE,
                         BUSINESS_TYPE, BUSINESS_ITEM, PHONE, MOBILE, EMAIL,
                         POSTAL_CODE, ADDRESS, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, ACTIVE_FLAG)
SELECT SEQ_PARTNER.NEXTVAL, LPAD(TO_CHAR(SEQ_PARTNER.NEXTVAL), 5, '0'), '대한전자', '123-81-00003', '윤재호',
       '제조', '전자부품', '032-1000-0003', '010-0000-0003', 'daehan@example.com',
       '21984', '인천광역시 연수구 컨벤시아대로 80',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00003'), '박민수', NULL, 'Y'
  FROM DUAL;

-- 00004 서울오피스 (담당 김철수)
INSERT INTO BIZ_PARTNER (PARTNER_ID, PARTNER_CODE, PARTNER_NAME, BUSINESS_NO, REPRESENTATIVE,
                         BUSINESS_TYPE, BUSINESS_ITEM, PHONE, MOBILE, EMAIL,
                         POSTAL_CODE, ADDRESS, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, ACTIVE_FLAG)
SELECT SEQ_PARTNER.NEXTVAL, LPAD(TO_CHAR(SEQ_PARTNER.NEXTVAL), 5, '0'), '서울오피스', '123-81-00004', '송하늘',
       '서비스', '사무환경 구축', '02-1000-0004', '010-0000-0004', 'seouloffice@example.com',
       '04536', '서울특별시 중구 을지로 50',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00001'), '김철수', NULL, 'Y'
  FROM DUAL;

-- 00005 누리테크 (담당 이영희)
INSERT INTO BIZ_PARTNER (PARTNER_ID, PARTNER_CODE, PARTNER_NAME, BUSINESS_NO, REPRESENTATIVE,
                         BUSINESS_TYPE, BUSINESS_ITEM, PHONE, MOBILE, EMAIL,
                         POSTAL_CODE, ADDRESS, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, ACTIVE_FLAG)
SELECT SEQ_PARTNER.NEXTVAL, LPAD(TO_CHAR(SEQ_PARTNER.NEXTVAL), 5, '0'), '누리테크', '123-81-00005', '배준영',
       '도소매', '소프트웨어 및 주변기기', '042-1000-0005', '010-0000-0005', 'nuritech@example.com',
       '34051', '대전광역시 유성구 엑스포로 60',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00002'), '이영희', NULL, 'Y'
  FROM DUAL;

-- 00006 동해물산 (담당 박민수) : 사용중단
INSERT INTO BIZ_PARTNER (PARTNER_ID, PARTNER_CODE, PARTNER_NAME, BUSINESS_NO, REPRESENTATIVE,
                         BUSINESS_TYPE, BUSINESS_ITEM, PHONE, MOBILE, EMAIL,
                         POSTAL_CODE, ADDRESS, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, ACTIVE_FLAG)
SELECT SEQ_PARTNER.NEXTVAL, LPAD(TO_CHAR(SEQ_PARTNER.NEXTVAL), 5, '0'), '동해물산', '123-81-00006', '문지후',
       '도매', '생활잡화', '033-1000-0006', NULL, 'donghae@example.com',
       '25488', '강원특별자치도 강릉시 경강로 1200',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00003'), '박민수', '거래 중단 (사용중단 필터 확인용)', 'N'
  FROM DUAL;

-- ====================================================================
-- 3. WAREHOUSE (창고 4건 : 창고 2 + 공장 1 + 사용중단 창고 1)
--    WAREHOUSE_TYPE : DDL 코멘트 '창고 또는 공장 중 선택' 기준으로 '창고' / '공장'
-- ====================================================================

-- 00001 본사창고 (창고)
INSERT INTO WAREHOUSE (WAREHOUSE_ID, WAREHOUSE_CODE, WAREHOUSE_NAME, WAREHOUSE_TYPE, ACTIVE_FLAG)
SELECT SEQ_WAREHOUSE.NEXTVAL, LPAD(TO_CHAR(SEQ_WAREHOUSE.NEXTVAL), 5, '0'), '본사창고', '창고', 'Y'
  FROM DUAL;

-- 00002 제2창고 (창고)
INSERT INTO WAREHOUSE (WAREHOUSE_ID, WAREHOUSE_CODE, WAREHOUSE_NAME, WAREHOUSE_TYPE, ACTIVE_FLAG)
SELECT SEQ_WAREHOUSE.NEXTVAL, LPAD(TO_CHAR(SEQ_WAREHOUSE.NEXTVAL), 5, '0'), '제2창고', '창고', 'Y'
  FROM DUAL;

-- 00003 생산공장 (공장)
INSERT INTO WAREHOUSE (WAREHOUSE_ID, WAREHOUSE_CODE, WAREHOUSE_NAME, WAREHOUSE_TYPE, ACTIVE_FLAG)
SELECT SEQ_WAREHOUSE.NEXTVAL, LPAD(TO_CHAR(SEQ_WAREHOUSE.NEXTVAL), 5, '0'), '생산공장', '공장', 'Y'
  FROM DUAL;

-- 00004 임시창고 (창고) : 사용중단
INSERT INTO WAREHOUSE (WAREHOUSE_ID, WAREHOUSE_CODE, WAREHOUSE_NAME, WAREHOUSE_TYPE, ACTIVE_FLAG)
SELECT SEQ_WAREHOUSE.NEXTVAL, LPAD(TO_CHAR(SEQ_WAREHOUSE.NEXTVAL), 5, '0'), '임시창고', '창고', 'N'
  FROM DUAL;

-- ====================================================================
-- 4. ITEM (품목 10건 : 사용 9 + 사용중단 1)
--    ITEM_TYPE : 원재료 / 부재료 / 제품 / 반제품 / 상품 / 무형상품 중 사용
--    OUTBOUND_PRICE : 견적/주문/판매 단가 초기값, IMAGE_PATH : 실제 파일이 없으므로 NULL
-- ====================================================================

-- 00001 노트북 (상품)
INSERT INTO ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, SPECIFICATION, UNIT, ITEM_TYPE,
                  INBOUND_PRICE, OUTBOUND_PRICE, NOTE, ACTIVE_FLAG)
SELECT SEQ_ITEM.NEXTVAL, LPAD(TO_CHAR(SEQ_ITEM.NEXTVAL), 5, '0'), '노트북', '15.6인치 / i5 / 16GB', 'EA', '상품',
       800000, 1000000, NULL, 'Y'
  FROM DUAL;

-- 00002 모니터 (상품)
INSERT INTO ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, SPECIFICATION, UNIT, ITEM_TYPE,
                  INBOUND_PRICE, OUTBOUND_PRICE, NOTE, ACTIVE_FLAG)
SELECT SEQ_ITEM.NEXTVAL, LPAD(TO_CHAR(SEQ_ITEM.NEXTVAL), 5, '0'), '모니터', '27인치 / QHD', 'EA', '상품',
       150000, 200000, NULL, 'Y'
  FROM DUAL;

-- 00003 키보드 (상품)
INSERT INTO ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, SPECIFICATION, UNIT, ITEM_TYPE,
                  INBOUND_PRICE, OUTBOUND_PRICE, NOTE, ACTIVE_FLAG)
SELECT SEQ_ITEM.NEXTVAL, LPAD(TO_CHAR(SEQ_ITEM.NEXTVAL), 5, '0'), '키보드', '기계식 / 텐키리스', 'EA', '상품',
       40000, 50000, NULL, 'Y'
  FROM DUAL;

-- 00004 마우스 (상품)
INSERT INTO ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, SPECIFICATION, UNIT, ITEM_TYPE,
                  INBOUND_PRICE, OUTBOUND_PRICE, NOTE, ACTIVE_FLAG)
SELECT SEQ_ITEM.NEXTVAL, LPAD(TO_CHAR(SEQ_ITEM.NEXTVAL), 5, '0'), '마우스', '무선 / 블루투스', 'EA', '상품',
       15000, 20000, NULL, 'Y'
  FROM DUAL;

-- 00005 USB 허브 (상품)
INSERT INTO ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, SPECIFICATION, UNIT, ITEM_TYPE,
                  INBOUND_PRICE, OUTBOUND_PRICE, NOTE, ACTIVE_FLAG)
SELECT SEQ_ITEM.NEXTVAL, LPAD(TO_CHAR(SEQ_ITEM.NEXTVAL), 5, '0'), 'USB 허브', 'USB-C / 7포트', 'EA', '상품',
       20000, 30000, NULL, 'Y'
  FROM DUAL;

-- 00006 노트북 거치대 (제품)
INSERT INTO ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, SPECIFICATION, UNIT, ITEM_TYPE,
                  INBOUND_PRICE, OUTBOUND_PRICE, NOTE, ACTIVE_FLAG)
SELECT SEQ_ITEM.NEXTVAL, LPAD(TO_CHAR(SEQ_ITEM.NEXTVAL), 5, '0'), '노트북 거치대', '알루미늄 / 각도조절', 'EA', '제품',
       25000, 40000, NULL, 'Y'
  FROM DUAL;

-- 00007 거치대 프레임 (반제품)
INSERT INTO ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, SPECIFICATION, UNIT, ITEM_TYPE,
                  INBOUND_PRICE, OUTBOUND_PRICE, NOTE, ACTIVE_FLAG)
SELECT SEQ_ITEM.NEXTVAL, LPAD(TO_CHAR(SEQ_ITEM.NEXTVAL), 5, '0'), '거치대 프레임', '알루미늄 / 절곡', 'EA', '반제품',
       12000, 15000, NULL, 'Y'
  FROM DUAL;

-- 00008 알루미늄 판재 (원재료)
INSERT INTO ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, SPECIFICATION, UNIT, ITEM_TYPE,
                  INBOUND_PRICE, OUTBOUND_PRICE, NOTE, ACTIVE_FLAG)
SELECT SEQ_ITEM.NEXTVAL, LPAD(TO_CHAR(SEQ_ITEM.NEXTVAL), 5, '0'), '알루미늄 판재', '300x300x3T', '장', '원재료',
       8000, 10000, NULL, 'Y'
  FROM DUAL;

-- 00009 설치 서비스 (무형상품)
INSERT INTO ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, SPECIFICATION, UNIT, ITEM_TYPE,
                  INBOUND_PRICE, OUTBOUND_PRICE, NOTE, ACTIVE_FLAG)
SELECT SEQ_ITEM.NEXTVAL, LPAD(TO_CHAR(SEQ_ITEM.NEXTVAL), 5, '0'), '설치 서비스', '방문 설치 1회', '회', '무형상품',
       30000, 50000, NULL, 'Y'
  FROM DUAL;

-- 00010 유선 마우스 (상품) : 사용중단
INSERT INTO ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, SPECIFICATION, UNIT, ITEM_TYPE,
                  INBOUND_PRICE, OUTBOUND_PRICE, NOTE, ACTIVE_FLAG)
SELECT SEQ_ITEM.NEXTVAL, LPAD(TO_CHAR(SEQ_ITEM.NEXTVAL), 5, '0'), '유선 마우스', 'USB 유선', 'EA', '상품',
       5000, 8000, '단종 (사용중단 필터 확인용)', 'N'
  FROM DUAL;

-- ====================================================================
-- 5. QUOTATION (견적서 5건)
--    PROGRESS_STATUS : UNCONFIRMED / IN_PROGRESS / COMPLETED
-- ====================================================================

-- 견적 00001 | [1] 견적만 : 주문 0 (미주문 현황에 전량 표시)
INSERT INTO QUOTATION (QUOTATION_ID, QUOTATION_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                       WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS)
SELECT SEQ_QUOTATION.NEXTVAL, LPAD(TO_CHAR(SEQ_QUOTATION.NEXTVAL), 5, '0'), DATE '2026-09-01',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00001'), '한빛상사',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00001'), '김철수',
       '신규 사무실 장비 견적', 'IN_PROGRESS'
  FROM DUAL;

-- 견적 00002 | [2] 부분 주문 : 주문서 2건(00001, 00003)으로 나누어 일부만 주문
INSERT INTO QUOTATION (QUOTATION_ID, QUOTATION_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                       WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS)
SELECT SEQ_QUOTATION.NEXTVAL, LPAD(TO_CHAR(SEQ_QUOTATION.NEXTVAL), 5, '0'), DATE '2026-09-02',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00002'), '미래유통',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00002'), '이영희',
       '모니터 교체 견적 - 2회 분할 주문 진행 중', 'IN_PROGRESS'
  FROM DUAL;

-- 견적 00003 | [3] 전부 주문 : 미주문 0 (미주문 현황에서 제외)
INSERT INTO QUOTATION (QUOTATION_ID, QUOTATION_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                       WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS)
SELECT SEQ_QUOTATION.NEXTVAL, LPAD(TO_CHAR(SEQ_QUOTATION.NEXTVAL), 5, '0'), DATE '2026-09-03',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00003'), '대한전자',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00003'), '박민수',
       '키보드 견적 - 전량 주문 완료', 'COMPLETED'
  FROM DUAL;

-- 견적 00004 | 삭제 필터 확인용 (고립 데이터) : 헤더/상세 DELETED_YN = 'Y', 연결 전표 없음
INSERT INTO QUOTATION (QUOTATION_ID, QUOTATION_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                       WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS, DELETED_YN)
SELECT SEQ_QUOTATION.NEXTVAL, LPAD(TO_CHAR(SEQ_QUOTATION.NEXTVAL), 5, '0'), DATE '2026-09-04',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00005'), '누리테크',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00002'), '이영희',
       '중복 작성 견적 - 삭제 처리', 'IN_PROGRESS', 'Y'
  FROM DUAL;

-- 견적 00005 | 상태 필터 확인용 (고립 데이터) : 미확인 + 창고 미지정(WAREHOUSE_ID NULL)
INSERT INTO QUOTATION (QUOTATION_ID, QUOTATION_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                       WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS)
SELECT SEQ_QUOTATION.NEXTVAL, LPAD(TO_CHAR(SEQ_QUOTATION.NEXTVAL), 5, '0'), DATE '2026-09-14',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00004'), '서울오피스',
       NULL, NULL,
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00001'), '김철수',
       '회의실 USB 허브 견적 - 확인 대기', 'UNCONFIRMED'
  FROM DUAL;

-- ====================================================================
-- 6. QUOTATION_LINE (견적서 상세 6건)
--    같은 견적서 안에서 품목이 겹치지 않으므로 견적번호 + 품목코드로 행을 식별
-- ====================================================================

-- [견적 00001 한빛상사]
-- 노트북 10 x 1,000,000 | 주문 0 > 미주문 10
INSERT INTO QUOTATION_LINE (QUOTATION_LINE_ID, QUOTATION_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                            QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT)
VALUES (SEQ_QUOTATION_LINE.NEXTVAL,
        (SELECT QUOTATION_ID FROM QUOTATION WHERE QUOTATION_NO = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00001'), '노트북', '15.6인치 / i5 / 16GB', 'EA',
        10, 1000000, 10000000, 1000000, 11000000);
-- 모니터 5 x 200,000 | 주문 0 > 미주문 5
INSERT INTO QUOTATION_LINE (QUOTATION_LINE_ID, QUOTATION_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                            QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT)
VALUES (SEQ_QUOTATION_LINE.NEXTVAL,
        (SELECT QUOTATION_ID FROM QUOTATION WHERE QUOTATION_NO = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), '모니터', '27인치 / QHD', 'EA',
        5, 200000, 1000000, 100000, 1100000);

-- [견적 00002 미래유통]
-- 모니터 10 x 195,000 | 주문 4 + 2 = 6 > 미주문 4
INSERT INTO QUOTATION_LINE (QUOTATION_LINE_ID, QUOTATION_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                            QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT)
VALUES (SEQ_QUOTATION_LINE.NEXTVAL,
        (SELECT QUOTATION_ID FROM QUOTATION WHERE QUOTATION_NO = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), '모니터', '27인치 / QHD', 'EA',
        10, 195000, 1950000, 195000, 2145000);

-- [견적 00003 대한전자]
-- 키보드 10 x 50,000 | 주문 10 > 미주문 0
INSERT INTO QUOTATION_LINE (QUOTATION_LINE_ID, QUOTATION_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                            QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT)
VALUES (SEQ_QUOTATION_LINE.NEXTVAL,
        (SELECT QUOTATION_ID FROM QUOTATION WHERE QUOTATION_NO = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), '키보드', '기계식 / 텐키리스', 'EA',
        10, 50000, 500000, 50000, 550000);

-- [견적 00004 누리테크]
-- 마우스 30 x 20,000 | 삭제된 행 > 미주문 계산에서 제외
INSERT INTO QUOTATION_LINE (QUOTATION_LINE_ID, QUOTATION_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                            QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, DELETED_YN)
VALUES (SEQ_QUOTATION_LINE.NEXTVAL,
        (SELECT QUOTATION_ID FROM QUOTATION WHERE QUOTATION_NO = '00004'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), '마우스', '무선 / 블루투스', 'EA',
        30, 20000, 600000, 60000, 660000, 'Y');

-- [견적 00005 서울오피스]
-- USB 허브 20 x 30,000 | 주문 0 > 미주문 20 (미확인 견적)
INSERT INTO QUOTATION_LINE (QUOTATION_LINE_ID, QUOTATION_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                            QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT)
VALUES (SEQ_QUOTATION_LINE.NEXTVAL,
        (SELECT QUOTATION_ID FROM QUOTATION WHERE QUOTATION_NO = '00005'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00005'), 'USB 허브', 'USB-C / 7포트', 'EA',
        20, 30000, 600000, 60000, 660000);

-- ====================================================================
-- 7. SALES_ORDER (주문서 6건)
--    PROGRESS_STATUS : UNCONFIRMED / IN_PROGRESS / COMPLETED
-- ====================================================================

-- 주문 00001 | [2] 견적 00002 1차 주문 (판매 전)
INSERT INTO SALES_ORDER (SALES_ORDER_ID, SALES_ORDER_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                         WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, DUE_DATE, NOTE, PROGRESS_STATUS)
SELECT SEQ_SALES_ORDER.NEXTVAL, LPAD(TO_CHAR(SEQ_SALES_ORDER.NEXTVAL), 5, '0'), DATE '2026-09-03',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00002'), '미래유통',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00002'), '이영희',
       DATE '2026-09-10', '견적 00002 1차 주문', 'IN_PROGRESS'
  FROM DUAL;

-- 주문 00002 | [3] 견적 00003 전량 주문 + [6] 전부 판매된 주문 (판매 00001, 00002)
INSERT INTO SALES_ORDER (SALES_ORDER_ID, SALES_ORDER_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                         WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, DUE_DATE, NOTE, PROGRESS_STATUS)
SELECT SEQ_SALES_ORDER.NEXTVAL, LPAD(TO_CHAR(SEQ_SALES_ORDER.NEXTVAL), 5, '0'), DATE '2026-09-04',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00003'), '대한전자',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00003'), '박민수',
       DATE '2026-09-08', '견적 00003 전량 주문', 'COMPLETED'
  FROM DUAL;

-- 주문 00003 | [2] 견적 00002 2차 주문 (판매 전) : 같은 견적 행을 두 번째로 참조
INSERT INTO SALES_ORDER (SALES_ORDER_ID, SALES_ORDER_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                         WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, DUE_DATE, NOTE, PROGRESS_STATUS)
SELECT SEQ_SALES_ORDER.NEXTVAL, LPAD(TO_CHAR(SEQ_SALES_ORDER.NEXTVAL), 5, '0'), DATE '2026-09-06',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00002'), '미래유통',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00002'), '이영희',
       DATE '2026-09-13', '견적 00002 2차 주문', 'IN_PROGRESS'
  FROM DUAL;

-- 주문 00004 | [5] 부분 판매 + [10] 직접 주문 : 노트북은 일부만, 마우스는 전량 판매
INSERT INTO SALES_ORDER (SALES_ORDER_ID, SALES_ORDER_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                         WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, DUE_DATE, NOTE, PROGRESS_STATUS)
SELECT SEQ_SALES_ORDER.NEXTVAL, LPAD(TO_CHAR(SEQ_SALES_ORDER.NEXTVAL), 5, '0'), DATE '2026-09-07',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00004'), '서울오피스',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'), '제2창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00001'), '김철수',
       DATE '2026-09-20', '견적 없이 직접 주문', 'IN_PROGRESS'
  FROM DUAL;

-- 주문 00005 | [4] 주문만 + [10] 직접 주문 : 판매 0
INSERT INTO SALES_ORDER (SALES_ORDER_ID, SALES_ORDER_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                         WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, DUE_DATE, NOTE, PROGRESS_STATUS)
SELECT SEQ_SALES_ORDER.NEXTVAL, LPAD(TO_CHAR(SEQ_SALES_ORDER.NEXTVAL), 5, '0'), DATE '2026-09-09',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00005'), '누리테크',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00002'), '이영희',
       DATE '2026-09-25', '견적 없이 직접 주문 - 판매 대기', 'IN_PROGRESS'
  FROM DUAL;

-- 주문 00006 | 상태 필터 확인용 (고립 데이터) : 미확인 직접 주문, 납기일 미정
INSERT INTO SALES_ORDER (SALES_ORDER_ID, SALES_ORDER_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                         WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, DUE_DATE, NOTE, PROGRESS_STATUS)
SELECT SEQ_SALES_ORDER.NEXTVAL, LPAD(TO_CHAR(SEQ_SALES_ORDER.NEXTVAL), 5, '0'), DATE '2026-09-17',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00001'), '한빛상사',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00001'), '김철수',
       NULL, '직접 주문 - 확인 대기', 'UNCONFIRMED'
  FROM DUAL;

-- ====================================================================
-- 8. SALES_ORDER_LINE (주문서 상세 7건)
--    QUOTATION_LINE_ID : 원견적 상세행 (직접 주문은 NULL)
--    미주문 = 견적수량 - 해당 견적행을 참조하는 유효 주문행 수량 합계
-- ====================================================================

-- [주문 00001 미래유통]
-- 모니터 4 x 195,000 | 원견적 00002 모니터 행 | 판매 0 > 미판매 4
INSERT INTO SALES_ORDER_LINE (SALES_ORDER_LINE_ID, SALES_ORDER_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                              QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, QUOTATION_LINE_ID)
VALUES (SEQ_SALES_ORDER_LINE.NEXTVAL,
        (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE SALES_ORDER_NO = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), '모니터', '27인치 / QHD', 'EA',
        4, 195000, 780000, 78000, 858000,
        (SELECT QL.QUOTATION_LINE_ID
           FROM QUOTATION_LINE QL
           JOIN QUOTATION Q ON Q.QUOTATION_ID = QL.QUOTATION_ID
           JOIN ITEM I ON I.ITEM_ID = QL.ITEM_ID
          WHERE Q.QUOTATION_NO = '00002' AND I.ITEM_CODE = '00002'));

-- [주문 00002 대한전자]
-- 키보드 10 x 50,000 | 원견적 00003 키보드 행 | 판매 6 + 4 = 10 > 미판매 0
INSERT INTO SALES_ORDER_LINE (SALES_ORDER_LINE_ID, SALES_ORDER_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                              QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, QUOTATION_LINE_ID)
VALUES (SEQ_SALES_ORDER_LINE.NEXTVAL,
        (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE SALES_ORDER_NO = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), '키보드', '기계식 / 텐키리스', 'EA',
        10, 50000, 500000, 50000, 550000,
        (SELECT QL.QUOTATION_LINE_ID
           FROM QUOTATION_LINE QL
           JOIN QUOTATION Q ON Q.QUOTATION_ID = QL.QUOTATION_ID
           JOIN ITEM I ON I.ITEM_ID = QL.ITEM_ID
          WHERE Q.QUOTATION_NO = '00003' AND I.ITEM_CODE = '00003'));

-- [주문 00003 미래유통]
-- 모니터 2 x 195,000 | 원견적 00002 모니터 행 | 판매 0 > 미판매 2
INSERT INTO SALES_ORDER_LINE (SALES_ORDER_LINE_ID, SALES_ORDER_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                              QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, QUOTATION_LINE_ID)
VALUES (SEQ_SALES_ORDER_LINE.NEXTVAL,
        (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE SALES_ORDER_NO = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), '모니터', '27인치 / QHD', 'EA',
        2, 195000, 390000, 39000, 429000,
        (SELECT QL.QUOTATION_LINE_ID
           FROM QUOTATION_LINE QL
           JOIN QUOTATION Q ON Q.QUOTATION_ID = QL.QUOTATION_ID
           JOIN ITEM I ON I.ITEM_ID = QL.ITEM_ID
          WHERE Q.QUOTATION_NO = '00002' AND I.ITEM_CODE = '00002'));

-- [주문 00004 서울오피스]
-- 노트북 10 x 1,000,000 | 직접 주문 (QUOTATION_LINE_ID = NULL) | 판매 4 > 미판매 6
INSERT INTO SALES_ORDER_LINE (SALES_ORDER_LINE_ID, SALES_ORDER_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                              QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, QUOTATION_LINE_ID)
VALUES (SEQ_SALES_ORDER_LINE.NEXTVAL,
        (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE SALES_ORDER_NO = '00004'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00001'), '노트북', '15.6인치 / i5 / 16GB', 'EA',
        10, 1000000, 10000000, 1000000, 11000000, NULL);
-- 마우스 10 x 19,000 | 직접 주문 (QUOTATION_LINE_ID = NULL) | 판매 10 > 미판매 0 (같은 주문의 완료 행)
INSERT INTO SALES_ORDER_LINE (SALES_ORDER_LINE_ID, SALES_ORDER_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                              QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, QUOTATION_LINE_ID)
VALUES (SEQ_SALES_ORDER_LINE.NEXTVAL,
        (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE SALES_ORDER_NO = '00004'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), '마우스', '무선 / 블루투스', 'EA',
        10, 19000, 190000, 19000, 209000, NULL);

-- [주문 00005 누리테크]
-- 노트북 거치대 10 x 40,000 | 직접 주문 (QUOTATION_LINE_ID = NULL) | 판매 0 > 미판매 10
INSERT INTO SALES_ORDER_LINE (SALES_ORDER_LINE_ID, SALES_ORDER_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                              QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, QUOTATION_LINE_ID)
VALUES (SEQ_SALES_ORDER_LINE.NEXTVAL,
        (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE SALES_ORDER_NO = '00005'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00006'), '노트북 거치대', '알루미늄 / 각도조절', 'EA',
        10, 40000, 400000, 40000, 440000, NULL);

-- [주문 00006 한빛상사]
-- USB 허브 15 x 30,000 | 직접 주문 (QUOTATION_LINE_ID = NULL) | 판매 0 > 미판매 15 (미확인 주문)
INSERT INTO SALES_ORDER_LINE (SALES_ORDER_LINE_ID, SALES_ORDER_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                              QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, QUOTATION_LINE_ID)
VALUES (SEQ_SALES_ORDER_LINE.NEXTVAL,
        (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE SALES_ORDER_NO = '00006'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00005'), 'USB 허브', 'USB-C / 7포트', 'EA',
        15, 30000, 450000, 45000, 495000, NULL);

-- ====================================================================
-- 9. SALE (판매 5건)
--    PROGRESS_STATUS : UNCONFIRMED / CONFIRMED
--    CREATED_AT / UPDATED_AT : 판매 단가 일괄 변경 화면 확인용으로 모두 명시
-- ====================================================================

-- 판매 00001 | [6] 주문 00002 불러오기 + 직접 행 추가 (작성 후 수정 없음)
INSERT INTO SALE (SALE_ID, SALE_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                  WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS,
                  CREATED_AT, UPDATED_AT)
SELECT SEQ_SALE.NEXTVAL, LPAD(TO_CHAR(SEQ_SALE.NEXTVAL), 5, '0'), DATE '2026-09-05',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00003'), '대한전자',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00003'), '박민수',
       '주문 00002 일부 판매 + 마우스 직접 추가', 'CONFIRMED',
       TIMESTAMP '2026-09-05 10:15:00', TIMESTAMP '2026-09-05 10:15:00'
  FROM DUAL;

-- 판매 00002 | [6] 주문 00002 잔량 판매 (다음 날 단가 수정 : 작성일시 != 수정일시)
INSERT INTO SALE (SALE_ID, SALE_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                  WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS,
                  CREATED_AT, UPDATED_AT)
SELECT SEQ_SALE.NEXTVAL, LPAD(TO_CHAR(SEQ_SALE.NEXTVAL), 5, '0'), DATE '2026-09-08',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00003'), '대한전자',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00003'), '박민수',
       '주문 00002 잔량 판매 - 단가 협의 48,000원', 'CONFIRMED',
       TIMESTAMP '2026-09-08 14:20:00', TIMESTAMP '2026-09-09 09:40:00'
  FROM DUAL;

-- 판매 00003 | [5] 주문 00004 불러오기 : 노트북 일부 + 마우스 전량
INSERT INTO SALE (SALE_ID, SALE_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                  WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS,
                  CREATED_AT, UPDATED_AT)
SELECT SEQ_SALE.NEXTVAL, LPAD(TO_CHAR(SEQ_SALE.NEXTVAL), 5, '0'), DATE '2026-09-10',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00004'), '서울오피스',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'), '제2창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00001'), '김철수',
       '주문 00004 부분 판매', 'CONFIRMED',
       TIMESTAMP '2026-09-10 11:05:00', TIMESTAMP '2026-09-10 11:05:00'
  FROM DUAL;

-- 판매 00004 | [10] 직접 판매 : 업무일자(09-12)보다 늦게 작성(09-14), 이후 수정
INSERT INTO SALE (SALE_ID, SALE_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                  WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS,
                  CREATED_AT, UPDATED_AT)
SELECT SEQ_SALE.NEXTVAL, LPAD(TO_CHAR(SEQ_SALE.NEXTVAL), 5, '0'), DATE '2026-09-12',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00001'), '한빛상사',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00001'), '김철수',
       '주문 없이 직접 판매', 'CONFIRMED',
       TIMESTAMP '2026-09-14 16:30:00', TIMESTAMP '2026-09-15 10:20:00'
  FROM DUAL;

-- 판매 00005 | 상태 필터 확인용 : 미확인 직접 판매 (판매 저장 시 차감 규칙에 따라 재고 반영)
INSERT INTO SALE (SALE_ID, SALE_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                  WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS,
                  CREATED_AT, UPDATED_AT)
SELECT SEQ_SALE.NEXTVAL, LPAD(TO_CHAR(SEQ_SALE.NEXTVAL), 5, '0'), DATE '2026-09-15',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00005'), '누리테크',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00003'), '생산공장',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00002'), '이영희',
       '직접 판매 - 확인 대기', 'UNCONFIRMED',
       TIMESTAMP '2026-09-15 17:45:00', TIMESTAMP '2026-09-15 17:45:00'
  FROM DUAL;

-- ====================================================================
-- 10. SALE_LINE (판매 상세 9건)
--    SALES_ORDER_LINE_ID : 원주문 상세행 (직접 판매 행은 NULL)
--    미판매 = 주문수량 - 해당 주문행을 참조하는 유효 판매행 수량 합계
-- ====================================================================

-- [판매 00001 대한전자 / 본사창고]
-- 키보드 6 x 50,000 | 원주문 00002 키보드 행 | 출하지시 6
INSERT INTO SALE_LINE (SALE_LINE_ID, SALE_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                       QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, SALES_ORDER_LINE_ID)
VALUES (SEQ_SALE_LINE.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), '키보드', '기계식 / 텐키리스', 'EA',
        6, 50000, 300000, 30000, 330000,
        (SELECT OL.SALES_ORDER_LINE_ID
           FROM SALES_ORDER_LINE OL
           JOIN SALES_ORDER O ON O.SALES_ORDER_ID = OL.SALES_ORDER_ID
           JOIN ITEM I ON I.ITEM_ID = OL.ITEM_ID
          WHERE O.SALES_ORDER_NO = '00002' AND I.ITEM_CODE = '00003'));
-- 마우스 5 x 20,000 | 직접 판매 행 (SALES_ORDER_LINE_ID = NULL) | 주문 없이 추가한 행, 출하지시 3 (잔량 2)
INSERT INTO SALE_LINE (SALE_LINE_ID, SALE_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                       QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, SALES_ORDER_LINE_ID)
VALUES (SEQ_SALE_LINE.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), '마우스', '무선 / 블루투스', 'EA',
        5, 20000, 100000, 10000, 110000, NULL);

-- [판매 00002 대한전자 / 본사창고]
-- 키보드 4 x 48,000 | 원주문 00002 키보드 행 | 출하지시 전
INSERT INTO SALE_LINE (SALE_LINE_ID, SALE_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                       QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, SALES_ORDER_LINE_ID)
VALUES (SEQ_SALE_LINE.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), '키보드', '기계식 / 텐키리스', 'EA',
        4, 48000, 192000, 19200, 211200,
        (SELECT OL.SALES_ORDER_LINE_ID
           FROM SALES_ORDER_LINE OL
           JOIN SALES_ORDER O ON O.SALES_ORDER_ID = OL.SALES_ORDER_ID
           JOIN ITEM I ON I.ITEM_ID = OL.ITEM_ID
          WHERE O.SALES_ORDER_NO = '00002' AND I.ITEM_CODE = '00003'));

-- [판매 00003 서울오피스 / 제2창고]
-- 노트북 4 x 1,000,000 | 원주문 00004 노트북 행 | 출하지시 4
INSERT INTO SALE_LINE (SALE_LINE_ID, SALE_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                       QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, SALES_ORDER_LINE_ID)
VALUES (SEQ_SALE_LINE.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00001'), '노트북', '15.6인치 / i5 / 16GB', 'EA',
        4, 1000000, 4000000, 400000, 4400000,
        (SELECT OL.SALES_ORDER_LINE_ID
           FROM SALES_ORDER_LINE OL
           JOIN SALES_ORDER O ON O.SALES_ORDER_ID = OL.SALES_ORDER_ID
           JOIN ITEM I ON I.ITEM_ID = OL.ITEM_ID
          WHERE O.SALES_ORDER_NO = '00004' AND I.ITEM_CODE = '00001'));
-- 마우스 10 x 19,000 | 원주문 00004 마우스 행 | 출하지시 전
INSERT INTO SALE_LINE (SALE_LINE_ID, SALE_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                       QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, SALES_ORDER_LINE_ID)
VALUES (SEQ_SALE_LINE.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), '마우스', '무선 / 블루투스', 'EA',
        10, 19000, 190000, 19000, 209000,
        (SELECT OL.SALES_ORDER_LINE_ID
           FROM SALES_ORDER_LINE OL
           JOIN SALES_ORDER O ON O.SALES_ORDER_ID = OL.SALES_ORDER_ID
           JOIN ITEM I ON I.ITEM_ID = OL.ITEM_ID
          WHERE O.SALES_ORDER_NO = '00004' AND I.ITEM_CODE = '00004'));

-- [판매 00004 한빛상사 / 본사창고]
-- 모니터 3 x 210,000 | 직접 판매 행 (SALES_ORDER_LINE_ID = NULL) | 출하지시 전
INSERT INTO SALE_LINE (SALE_LINE_ID, SALE_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                       QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, SALES_ORDER_LINE_ID)
VALUES (SEQ_SALE_LINE.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00004'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), '모니터', '27인치 / QHD', 'EA',
        3, 210000, 630000, 63000, 693000, NULL);
-- USB 허브 10 x 30,000 | 직접 판매 행 (SALES_ORDER_LINE_ID = NULL) | 출하지시 전
INSERT INTO SALE_LINE (SALE_LINE_ID, SALE_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                       QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, SALES_ORDER_LINE_ID)
VALUES (SEQ_SALE_LINE.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00004'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00005'), 'USB 허브', 'USB-C / 7포트', 'EA',
        10, 30000, 300000, 30000, 330000, NULL);
-- 키보드 2 x 52,000 | 직접 판매 행 (SALES_ORDER_LINE_ID = NULL) | 출하지시 전
INSERT INTO SALE_LINE (SALE_LINE_ID, SALE_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                       QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, SALES_ORDER_LINE_ID)
VALUES (SEQ_SALE_LINE.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00004'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), '키보드', '기계식 / 텐키리스', 'EA',
        2, 52000, 104000, 10400, 114400, NULL);

-- [판매 00005 누리테크 / 생산공장]
-- 노트북 거치대 5 x 40,000 | 직접 판매 행 (SALES_ORDER_LINE_ID = NULL) | 출하지시 전
INSERT INTO SALE_LINE (SALE_LINE_ID, SALE_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                       QUANTITY, UNIT_PRICE, SUPPLY_AMOUNT, VAT_AMOUNT, TOTAL_AMOUNT, SALES_ORDER_LINE_ID)
VALUES (SEQ_SALE_LINE.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00005'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00006'), '노트북 거치대', '알루미늄 / 각도조절', 'EA',
        5, 40000, 200000, 20000, 220000, NULL);

-- ====================================================================
-- 11. SHIP_INSTRUCTION (출하지시서 3건)
--    PROGRESS_STATUS : IN_PROGRESS / COMPLETED
-- ====================================================================

-- 출하지시 00001 | [8] 판매 00001 연계 : 키보드 전량 + 마우스 일부 지시 (일부 출하되어 진행중)
INSERT INTO SHIP_INSTRUCTION (SHIP_INSTRUCTION_ID, SHIP_INSTRUCTION_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                              WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PLANNED_DATE, PROGRESS_STATUS,
                              DELIVERY_CONTACT, DELIVERY_POSTAL_CODE, DELIVERY_ADDRESS)
SELECT SEQ_SHIP_INST.NEXTVAL, LPAD(TO_CHAR(SEQ_SHIP_INST.NEXTVAL), 5, '0'), DATE '2026-09-06',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00003'), '대한전자',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00003'), '박민수',
       '판매 00001 출하지시 - 마우스는 일부만 지시', DATE '2026-09-08', 'IN_PROGRESS',
       '010-0000-0003', '21984', '인천광역시 연수구 컨벤시아대로 80'
  FROM DUAL;

-- 출하지시 00002 | [8] 판매 00003 연계 : 노트북만 지시 (마우스 10은 미지시), 전량 출하되어 완료
INSERT INTO SHIP_INSTRUCTION (SHIP_INSTRUCTION_ID, SHIP_INSTRUCTION_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                              WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PLANNED_DATE, PROGRESS_STATUS,
                              DELIVERY_CONTACT, DELIVERY_POSTAL_CODE, DELIVERY_ADDRESS)
SELECT SEQ_SHIP_INST.NEXTVAL, LPAD(TO_CHAR(SEQ_SHIP_INST.NEXTVAL), 5, '0'), DATE '2026-09-11',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00004'), '서울오피스',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'), '제2창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00001'), '김철수',
       '판매 00003 노트북 출하지시', DATE '2026-09-12', 'COMPLETED',
       '010-0000-0004', '04536', '서울특별시 중구 을지로 50, 12층 회의실'
  FROM DUAL;

-- 출하지시 00003 | [10] 직접 출하지시 : 판매 없이 작성, 아직 출하 전
INSERT INTO SHIP_INSTRUCTION (SHIP_INSTRUCTION_ID, SHIP_INSTRUCTION_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                              WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PLANNED_DATE, PROGRESS_STATUS,
                              DELIVERY_CONTACT, DELIVERY_POSTAL_CODE, DELIVERY_ADDRESS)
SELECT SEQ_SHIP_INST.NEXTVAL, LPAD(TO_CHAR(SEQ_SHIP_INST.NEXTVAL), 5, '0'), DATE '2026-09-16',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00002'), '미래유통',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00002'), '이영희',
       '판매 없이 직접 출하지시 - 전시용 샘플', DATE '2026-09-18', 'IN_PROGRESS',
       '010-0000-0002', '13494', '경기도 성남시 분당구 판교역로 100'
  FROM DUAL;

-- ====================================================================
-- 12. SHIP_INSTRUCTION_LINE (출하지시서 상세 4건)
--    SALE_LINE_ID : 원판매 상세행 (직접 출하지시는 NULL)
-- ====================================================================

-- [출하지시 00001 대한전자]
-- 키보드 6 | 원판매 00001 키보드 행 | 판매 6 중 6 지시, 출하 4 > 미출하 2
INSERT INTO SHIP_INSTRUCTION_LINE (SHIP_INSTRUCTION_LINE_ID, SHIP_INSTRUCTION_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                                   QUANTITY, SALE_LINE_ID)
VALUES (SEQ_SHIP_INST_LINE.NEXTVAL,
        (SELECT SHIP_INSTRUCTION_ID FROM SHIP_INSTRUCTION WHERE SHIP_INSTRUCTION_NO = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), '키보드', '기계식 / 텐키리스', 'EA',
        6,
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00001' AND I.ITEM_CODE = '00003'));
-- 마우스 3 | 원판매 00001 마우스 행 | 판매 5 중 3 지시 (미지시 2), 출하 3 > 미출하 0
INSERT INTO SHIP_INSTRUCTION_LINE (SHIP_INSTRUCTION_LINE_ID, SHIP_INSTRUCTION_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                                   QUANTITY, SALE_LINE_ID)
VALUES (SEQ_SHIP_INST_LINE.NEXTVAL,
        (SELECT SHIP_INSTRUCTION_ID FROM SHIP_INSTRUCTION WHERE SHIP_INSTRUCTION_NO = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), '마우스', '무선 / 블루투스', 'EA',
        3,
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00001' AND I.ITEM_CODE = '00004'));

-- [출하지시 00002 서울오피스]
-- 노트북 4 | 원판매 00003 노트북 행 | 판매 4 중 4 지시, 출하 4 > 미출하 0
INSERT INTO SHIP_INSTRUCTION_LINE (SHIP_INSTRUCTION_LINE_ID, SHIP_INSTRUCTION_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                                   QUANTITY, SALE_LINE_ID)
VALUES (SEQ_SHIP_INST_LINE.NEXTVAL,
        (SELECT SHIP_INSTRUCTION_ID FROM SHIP_INSTRUCTION WHERE SHIP_INSTRUCTION_NO = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00001'), '노트북', '15.6인치 / i5 / 16GB', 'EA',
        4,
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00003' AND I.ITEM_CODE = '00001'));

-- [출하지시 00003 미래유통]
-- 모니터 2 | 직접 출하지시 (SALE_LINE_ID = NULL) | 출하 0 > 미출하 2
INSERT INTO SHIP_INSTRUCTION_LINE (SHIP_INSTRUCTION_LINE_ID, SHIP_INSTRUCTION_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                                   QUANTITY, SALE_LINE_ID)
VALUES (SEQ_SHIP_INST_LINE.NEXTVAL,
        (SELECT SHIP_INSTRUCTION_ID FROM SHIP_INSTRUCTION WHERE SHIP_INSTRUCTION_NO = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), '모니터', '27인치 / QHD', 'EA',
        2, NULL);

-- ====================================================================
-- 13. SHIPMENT (출하 3건)
--    PROGRESS_STATUS : UNCONFIRMED / CONFIRMED
-- ====================================================================

-- 출하 00001 | [9] 출하지시 00001 연계 : 키보드 일부 + 마우스 전량 출하
INSERT INTO SHIPMENT (SHIPMENT_ID, SHIPMENT_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                      WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS,
                      DELIVERY_CONTACT, DELIVERY_POSTAL_CODE, DELIVERY_ADDRESS)
SELECT SEQ_SHIPMENT.NEXTVAL, LPAD(TO_CHAR(SEQ_SHIPMENT.NEXTVAL), 5, '0'), DATE '2026-09-08',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00003'), '대한전자',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'), '본사창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00003'), '박민수',
       '출하지시 00001 부분 출하 - 키보드 2개 미출하', 'CONFIRMED',
       '010-0000-0003', '21984', '인천광역시 연수구 컨벤시아대로 80'
  FROM DUAL;

-- 출하 00002 | [9] 출하지시 00002 연계 : 전량 출하
INSERT INTO SHIPMENT (SHIPMENT_ID, SHIPMENT_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                      WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS,
                      DELIVERY_CONTACT, DELIVERY_POSTAL_CODE, DELIVERY_ADDRESS)
SELECT SEQ_SHIPMENT.NEXTVAL, LPAD(TO_CHAR(SEQ_SHIPMENT.NEXTVAL), 5, '0'), DATE '2026-09-12',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00004'), '서울오피스',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'), '제2창고',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00001'), '김철수',
       '출하지시 00002 전량 출하', 'CONFIRMED',
       '010-0000-0004', '04536', '서울특별시 중구 을지로 50, 12층 회의실'
  FROM DUAL;

-- 출하 00003 | [10] 직접 출하 + 상태 필터 확인용 (미확인)
INSERT INTO SHIPMENT (SHIPMENT_ID, SHIPMENT_NO, BUSINESS_DATE, PARTNER_ID, PARTNER_NAME,
                      WAREHOUSE_ID, WAREHOUSE_NAME, ASSIGNEE_ID, ASSIGNEE_NAME, NOTE, PROGRESS_STATUS,
                      DELIVERY_CONTACT, DELIVERY_POSTAL_CODE, DELIVERY_ADDRESS)
SELECT SEQ_SHIPMENT.NEXTVAL, LPAD(TO_CHAR(SEQ_SHIPMENT.NEXTVAL), 5, '0'), DATE '2026-09-17',
       (SELECT PARTNER_ID FROM BIZ_PARTNER WHERE PARTNER_CODE = '00005'), '누리테크',
       (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00003'), '생산공장',
       (SELECT ASSIGNEE_ID FROM ASSIGNEE WHERE ASSIGNEE_CODE = '00002'), '이영희',
       '출하지시 없이 직접 출하 - 샘플, 확인 대기', 'UNCONFIRMED',
       '010-0000-0005', '34051', '대전광역시 유성구 엑스포로 60'
  FROM DUAL;

-- ====================================================================
-- 14. SHIPMENT_LINE (출하 상세 4건)
--    SHIP_INSTRUCTION_LINE_ID : 원출하지시 상세행 (직접 출하는 NULL)
-- ====================================================================

-- [출하 00001 대한전자]
-- 키보드 4 | 원출하지시 00001 키보드 행 | 지시 6 중 4 출하
INSERT INTO SHIPMENT_LINE (SHIPMENT_LINE_ID, SHIPMENT_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                           QUANTITY, SHIP_INSTRUCTION_LINE_ID)
VALUES (SEQ_SHIPMENT_LINE.NEXTVAL,
        (SELECT SHIPMENT_ID FROM SHIPMENT WHERE SHIPMENT_NO = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), '키보드', '기계식 / 텐키리스', 'EA',
        4,
        (SELECT IL.SHIP_INSTRUCTION_LINE_ID
           FROM SHIP_INSTRUCTION_LINE IL
           JOIN SHIP_INSTRUCTION SI ON SI.SHIP_INSTRUCTION_ID = IL.SHIP_INSTRUCTION_ID
           JOIN ITEM I ON I.ITEM_ID = IL.ITEM_ID
          WHERE SI.SHIP_INSTRUCTION_NO = '00001' AND I.ITEM_CODE = '00003'));
-- 마우스 3 | 원출하지시 00001 마우스 행 | 지시 3 중 3 출하
INSERT INTO SHIPMENT_LINE (SHIPMENT_LINE_ID, SHIPMENT_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                           QUANTITY, SHIP_INSTRUCTION_LINE_ID)
VALUES (SEQ_SHIPMENT_LINE.NEXTVAL,
        (SELECT SHIPMENT_ID FROM SHIPMENT WHERE SHIPMENT_NO = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), '마우스', '무선 / 블루투스', 'EA',
        3,
        (SELECT IL.SHIP_INSTRUCTION_LINE_ID
           FROM SHIP_INSTRUCTION_LINE IL
           JOIN SHIP_INSTRUCTION SI ON SI.SHIP_INSTRUCTION_ID = IL.SHIP_INSTRUCTION_ID
           JOIN ITEM I ON I.ITEM_ID = IL.ITEM_ID
          WHERE SI.SHIP_INSTRUCTION_NO = '00001' AND I.ITEM_CODE = '00004'));

-- [출하 00002 서울오피스]
-- 노트북 4 | 원출하지시 00002 노트북 행 | 지시 4 중 4 출하
INSERT INTO SHIPMENT_LINE (SHIPMENT_LINE_ID, SHIPMENT_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                           QUANTITY, SHIP_INSTRUCTION_LINE_ID)
VALUES (SEQ_SHIPMENT_LINE.NEXTVAL,
        (SELECT SHIPMENT_ID FROM SHIPMENT WHERE SHIPMENT_NO = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00001'), '노트북', '15.6인치 / i5 / 16GB', 'EA',
        4,
        (SELECT IL.SHIP_INSTRUCTION_LINE_ID
           FROM SHIP_INSTRUCTION_LINE IL
           JOIN SHIP_INSTRUCTION SI ON SI.SHIP_INSTRUCTION_ID = IL.SHIP_INSTRUCTION_ID
           JOIN ITEM I ON I.ITEM_ID = IL.ITEM_ID
          WHERE SI.SHIP_INSTRUCTION_NO = '00002' AND I.ITEM_CODE = '00001'));

-- [출하 00003 누리테크]
-- 노트북 거치대 2 | 직접 출하 (SHIP_INSTRUCTION_LINE_ID = NULL) | 출하지시 없음
INSERT INTO SHIPMENT_LINE (SHIPMENT_LINE_ID, SHIPMENT_ID, ITEM_ID, ITEM_NAME, SPECIFICATION, UNIT,
                           QUANTITY, SHIP_INSTRUCTION_LINE_ID)
VALUES (SEQ_SHIPMENT_LINE.NEXTVAL,
        (SELECT SHIPMENT_ID FROM SHIPMENT WHERE SHIPMENT_NO = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00006'), '노트북 거치대', '알루미늄 / 각도조절', 'EA',
        2, NULL);

-- ====================================================================
-- 15. STOCK (현재고 12건 : 창고 + 품목 조합당 1행)
--    현재고 = 초기 재고 + 재고조정 + 판매 차감 (출하지시/출하는 반영하지 않음)
-- ====================================================================

-- 본사창고 노트북 : 초기 50 = 50
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00001'), 50);

-- 본사창고 모니터 : 초기 80, 판매 00004 -3 = 77
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), 77);

-- 본사창고 키보드 : 초기 100, 판매 00001 -6, 판매 00002 -4, 판매 00004 -2 = 88
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), 88);

-- 본사창고 마우스 : 초기 150, 판매 00001 -5 = 145
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), 145);

-- 본사창고 USB 허브 : 초기 120, 판매 00004 -10 = 110
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00005'), 110);

-- 본사창고 노트북 거치대 : 초기 30 = 30
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00006'), 30);

-- 제2창고 노트북 : 초기 30, 판매 00003 -4 = 26
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00001'), 26);

-- 제2창고 모니터 : 초기 40, 조정 -1 = 39
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), 39);

-- 제2창고 마우스 : 초기 60, 판매 00003 -10 = 50
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), 50);

-- 생산공장 노트북 거치대 : 초기 100, 판매 00005 -5 = 95
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00006'), 95);

-- 생산공장 거치대 프레임 : 초기 200 = 200
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00007'), 200);

-- 생산공장 알루미늄 판재 : 초기 500 = 500
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QUANTITY)
VALUES ((SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00008'), 500);

-- ====================================================================
-- 16. STOCK_MOVEMENT (재고 변동 이력 22건, 발생 시각 순)
--    재고조정 : SALE_ID / SALE_LINE_ID = NULL, 수량 + 또는 -
--    판매 차감 : SALE_ID / SALE_LINE_ID 지정, 수량 = -판매수량, 시각 = 판매 CREATED_AT
--    STOCK(창고+품목) 복합 FK를 참조하므로 STOCK 이후에 INSERT
-- ====================================================================

-- (1) 초기 재고 설정 : 간편 재고조정 +, 2026-09-01 09:00:00

-- 초기 재고 : 본사창고 노트북 +50
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00001'), 50, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 본사창고 모니터 +80
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), 80, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 본사창고 키보드 +100
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), 100, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 본사창고 마우스 +150
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), 150, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 본사창고 USB 허브 +120
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00005'), 120, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 본사창고 노트북 거치대 +30
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00006'), 30, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 제2창고 노트북 +30
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00001'), 30, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 제2창고 모니터 +40
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), 40, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 제2창고 마우스 +60
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), 60, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 생산공장 노트북 거치대 +100
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00006'), 100, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 생산공장 거치대 프레임 +200
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00007'), 200, TIMESTAMP '2026-09-01 09:00:00');

-- 초기 재고 : 생산공장 알루미늄 판재 +500
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00008'), 500, TIMESTAMP '2026-09-01 09:00:00');

-- (2) 이후 판매 차감과 재고조정 (발생 시각 순)

-- 판매 00001 : 본사창고 키보드 -6
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00001'),
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00001' AND I.ITEM_CODE = '00003'),
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), -6, TIMESTAMP '2026-09-05 10:15:00');

-- 판매 00001 : 본사창고 마우스 -5
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00001'),
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00001' AND I.ITEM_CODE = '00004'),
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), -5, TIMESTAMP '2026-09-05 10:15:00');

-- 판매 00002 : 본사창고 키보드 -4
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00002'),
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00002' AND I.ITEM_CODE = '00003'),
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), -4, TIMESTAMP '2026-09-08 14:20:00');

-- 판매 00003 : 제2창고 노트북 -4
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00003'),
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00003' AND I.ITEM_CODE = '00001'),
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00001'), -4, TIMESTAMP '2026-09-10 11:05:00');

-- 판매 00003 : 제2창고 마우스 -10
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00003'),
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00003' AND I.ITEM_CODE = '00004'),
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00004'), -10, TIMESTAMP '2026-09-10 11:05:00');

-- 재고조정 : 제2창고 모니터 파손 1개 (간편 재고조정) -1
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL, NULL, NULL,
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00002'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), -1, TIMESTAMP '2026-09-11 15:00:00');

-- 판매 00004 : 본사창고 모니터 -3
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00004'),
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00004' AND I.ITEM_CODE = '00002'),
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00002'), -3, TIMESTAMP '2026-09-14 16:30:00');

-- 판매 00004 : 본사창고 USB 허브 -10
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00004'),
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00004' AND I.ITEM_CODE = '00005'),
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00005'), -10, TIMESTAMP '2026-09-14 16:30:00');

-- 판매 00004 : 본사창고 키보드 -2
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00004'),
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00004' AND I.ITEM_CODE = '00003'),
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00001'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00003'), -2, TIMESTAMP '2026-09-14 16:30:00');

-- 판매 00005 : 생산공장 노트북 거치대 -5
INSERT INTO STOCK_MOVEMENT (MOVEMENT_ID, SALE_ID, SALE_LINE_ID, WAREHOUSE_ID, ITEM_ID,
                            QUANTITY_DELTA, OCCURRED_AT)
VALUES (SEQ_STOCK_MOVEMENT.NEXTVAL,
        (SELECT SALE_ID FROM SALE WHERE SALE_NO = '00005'),
        (SELECT SL.SALE_LINE_ID
           FROM SALE_LINE SL
           JOIN SALE S ON S.SALE_ID = SL.SALE_ID
           JOIN ITEM I ON I.ITEM_ID = SL.ITEM_ID
          WHERE S.SALE_NO = '00005' AND I.ITEM_CODE = '00006'),
        (SELECT WAREHOUSE_ID FROM WAREHOUSE WHERE WAREHOUSE_CODE = '00003'),
        (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = '00006'), -5, TIMESTAMP '2026-09-15 17:45:00');

-- ====================================================================
-- 전체 데이터 확정
-- ====================================================================

COMMIT;
